### ISSUE TITLE
Proxy setting overwritten applying set_peer_proxy, set_web_proxy etc. consecutively 

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1646]
Deluge 1.3 still has legacy peer_proxy, web_proxy etc. settings but unfortunately with 0.16 changing to a single proxy settings they end up overwriting the previous values. This is especially a problem if they are empty values. So if `peer_proxy` is set and `dht_proxy` is empty the final setting for `proxy` is empty.

I am not sure what the libtorrent solution should be but in Deluge I have applied a workaround so that with (>=0.16) only the `peer_proxy` is respected and all other proxies are not applied and those user-side settings are reset to empty.

**Comment by arvidn** [comment]
yeah, there's no obvious mapping there unfortunately. maybe the best way to be backwards compatible would be to keep separate settings slots for those, and then use the one that's set as the effective proxy. Do you have any ideas of how to do it?

**Comment by cas--** [comment]
Once an individual proxy has been set you would also store the type (e.g. `peer`) that set it and perhaps only that using that types method can clear or change the proxy? 

Alternatively the simpler option is that all other proxy type have no effect, other than peer?

Was thinking it's a bit late to sort in libtorrent and leave it to clients to deal with. I believe that is pretty much the case with 0.16 and 1.0 but 1.1 still has that code so feel something should be in place for that branch and the 1.1.2 release?

**Comment by arvidn** [comment]
what do you mean by "sort in libtorrent"?
when you say 1.1 still has that code, what do you refer to exactly? This change was primarily *removing* code, or rather, state. you mean it still has the semantics of just setting a single tracker for everything?

**Comment by cas--** [comment]
Yes the methods should have been removed rather than modified because setting the single proxy unknowingly overwrites when using the old style of proxy settings. 

And I mean it's a bug in every brach and since 1.1 is meant to be backward compatible it should be fixed for the imminent 1.1.2 release.

**Comment by cas--** [comment]
Since most uses would primarily set 'peer' I feel that the best course is to only parse that set method and noop for tracker, web and dht set methods.

**Comment by arvidn** [comment]
yeah, that makes sense. for trackers though, there's a separate flag to enable or disable the proxy for trackers (iirc), so settings and unsetting the tracker proxy could affect that flag.

still not clean backwards compatibility, but probably better than now

**Comment by cas--** [comment]
Ah yes, that seems reasonable.

**Comment by arvidn** [comment]
does this look reasonable? https://github.com/arvidn/libtorrent/pull/1664

**Comment by klkuznetsov** [comment]
Hello Dear Developers!  I have migrated from ubuntu 16.04 with libtorrent 0.13.6-1  to 18.04 with libtorrent: 1.1.5.0 and found this very bad improvement in deluged :

[WARNING ] 22:27:53 preferencesmanager:489 This version of libtorrent only supports a single proxy setting based upon 'peer' which will apply to all other other types.

A lot of users needs different proxy settings for peers, web, tracker and so on. This the main advantage of deluged based on libtorrent. For example in some countries  trackers web services is blocked, but udp/mtp traffic not blocked.  Why users should proxyfy  all traffic to the tor instead of only lists of seeds. With best regards.
Konstantin

**Comment by arvidn** [comment]
iiuc, in your example you would only need a single proxy that only applies to trackers. If you really need two *separate* proxies, what's the use case?

You can set `proxy_peer_connections` = false and `proxy_tracker_connections` = true for instance. It's documented [here](https://www.libtorrent.org/reference-Settings.html#proxy_peer_connections).

**Comment by klkuznetsov** [comment]
Arvidn, thanks for your answer!
Your are right, in my use case I need no proxy for peers and 1 proxy connections for  tracker (I use tor).
Thanks for workaround I'll try it.
But another use case may be:  remote VPS with socks5 for peers and another one proxy for tracker.
