### ISSUE TITLE
Potential bug in announce messages

### ISSUE THREAD

**Issue by the8472** [arvidn/libtorrent#193]
I'm occasionally seeing the error below in my logs.

It's basically closing the 'a' dictionary after the token key without a value. Possibly in cases where a value was omitted from a get_peers response.

```
failed to decode message  d1:ad2:id20:��$7a����*��>�imM1}=9:info_hash20:������I�=�����k�����4:porti6881e5:tokene1:q13:announce_peer1:t2:��1:v4:LT��1:y1:qe (length:128) from: /117.63.93.125:6881 reason:encountered 'e' (offset: 86) after dictionary key, expected a value
```

It might just be an old/already fixed bug since I'm not seeing it often.

**Comment by ssiloti** [comment]
I can't find any way that could have happened with the current code. The most obvious suspect would be that the token key's value was uninitialized, but I don't see how that could have happened.

The lack of a 'seed' key suggests the client is quite old. That key started being added unconditionally after 58d72301 which was committed in May of 2011. That being said, the relevant code hasn't changed much since then either. So it's not clear if this is a fixed bug, but the fact that it was seen from such an old (and presumably rare) client version suggests that it probably did get fixed at some point.

**Comment by arvidn** [comment]
do you know what the two bytes following "1:v4:LT" are? they encode the version (but with pretty low granularity)

**Comment by the8472** [comment]
more samples:

```
[2016-05-26T01:23:28.214292Z][Info] failed to decode message  d1:ad2:id20:�'(J��j���UQ�����W��9:info_hash20:"��c�6����z�J���GX��4:porti6881e5:tokene1:q13:announce_peer1:t2:��1:v4:LT��1:y1:qe (length:128) from: /113.235.112.80:6881 reason:encountered 'e' (offset: 86) after dictionary key, expected a value
[2016-05-26T01:23:31.160183Z][Info] failed to decode message  d1:ad2:id20:�ht�_.�����N�����"��9:info_hash20:"��c�6����z�J���GX��4:porti6881e5:tokene1:q13:announce_peer1:t2:��1:v4:LT��1:y1:qe (length:128) from: /104.157.239.169:6881 reason:encountered 'e' (offset: 86) after dictionary key, expected a value
[2016-05-26T01:23:31.184066Z][Info] failed to decode message  d1:ad2:id20:����������qI�&���1�m9:info_hash20:"��c�6����z�J���GX��4:porti6881e5:tokene1:q13:announce_peer1:t2:�E1:v4:LT��1:y1:qe (length:128) from: /36.48.103.117:16805 reason:encountered 'e' (offset: 86) after dictionary key, expected a value
```

followup pings showed that these nodes were using `LT��/0x4C540109`

So that's newer than the commit you've linked

**Comment by arvidn** [comment]
hm. the token value is missing there. I'll take a look

**Comment by arvidn** [comment]
The only way I can imagine the encoding producing this is if the token value is the *none* type (which asserts in debug builds). It probably makes sense to output an empty string in that case for release builds, to at least produce correct encoding.

The "seed" key is still missing in these messages though, which is suspicious. It was added in version 0.16, 5 years ago.

I've pushed this attempt to mitigate the issue: https://github.com/arvidn/libtorrent/commit/77c002d23fdc688c2cb3f5c66c85604009fa647d

**Comment by arvidn** [comment]
and this: https://github.com/arvidn/libtorrent/pull/756

**Comment by the8472** [comment]
Does libtorrent check whether a get_peers response contains a token? Responses that don't can be used for their nodes and values but are not eligible for announces.

**Comment by the8472** [comment]
Also, sending a 0-length token will just shift your problem from sending an invalid-bencoding anounce to a invalid-token announce.

**Comment by arvidn** [comment]
yes, if there's no token, the node is not forwarded to the announce function: https://github.com/arvidn/libtorrent/blob/RC_1_1/src/kademlia/find_data.cpp#L166
