### ISSUE TITLE
Simultaneously announcing IPv4 and IPv6 addresses

### ISSUE THREAD

**Issue by lovesyk** [arvidn/libtorrent#2255]
**Please provide the following information**

libtorrent version (or branch):

1.1.4

platform/architecture:

Debian Stretch x86-64 (Deluge)

compiler and compiler version:

Those used by the debian package / pre-compiled binaries for Ubuntu

please describe what symptom you see, what you would expect to see instead and
how to reproduce it:

After postponing the update to 1.x as long as possible (0.16.18 on Debian Jessie works fine) but now Debian stable having reached 1.1.1 with the issue still in place, I hope it can be solved. The issue seems similar to https://github.com/arvidn/libtorrent/issues/219 but its resolution did not solve this one.

I'm trying to announce both my IPv4 and IPv6 addresses to trackers which resulted in me trying the following configurations:

-  Binding to all addresses results in the client connecting to the tracker using the address it resolves to and not supplying either "ip" or "ipv6" parameters. If the tracker resolves to an v4 address, it only receives my IPv4 address and the same with IPv6.

- Binding to only IPv4 results in the same outcome except the tracker will obviously only see my IPv4 address.

- Binding to only IPv6 results in the client appending the "ipv6" parameter and the tracker receiving only the IPv6 address (two times).

- When binding to all addresses it's possible to use announce_ip which seems to work for both v4 and v6 according to NexusPHP. If one guesses the address family the tracker resolves to (or just forces it using /etc/hosts), it's possible to add the "missing" other address that way. This seems to be the only way to currently pass both v4 and v6 to it while also listening to both addresses.

To be sure the culprit are not these conditions:
https://github.com/arvidn/libtorrent/pull/597/files#diff-19929347e18a6ff1fc37f09ec720306bR3147 I compiled 1.1.4 without them without any change.

A bit off-topic but I don't understand the reason for the latter condition. In a regular scenario I'd want to connect to as many peers as possible, private torrent or not. This obviously includes peers having only an IPv6 address (which at some point in the future will be the whole swarm).

**Comment by arvidn** [comment]
I'm not sure what scenario you have. My understanding is:

* Your computer has one IPv4 address and one IPv6 address.
* The tracker you're announcing to can only be reached via an IPv4 address
* in order for the tracker to track your IPv6 address you need the ``&ipv6=`` parameter to be passed along to the tracker.

Is that right?
What's the actual symtom you experience? Is it that the ``&ipv6=`` parameter is not passed to the tracker?

Anyway, this case is only supported for private torrents, and mostly for backwards compatibility.

The conditions you refer to is there to support this case for private torrents only. The reason to *not* send the IPv6 address is that your understanding of your address may not be the address other peers reach you over. That's why it's always preferred to have the tracker accept announces over each address family it supports (i.e. both IPv6 and IPv4). Consider the case where you're using a proxy, a VPN or NAT. In either of those cases, passing along your IPv6 address may be a burden to the swarms (if nobody can connect to you) to an information leak that you may not want.

**Comment by lovesyk** [comment]
My scenario is:
  - My computer has one IPv4 address and one IPv6 address.
  - The tracker I'm announcing to can be reached through both IPv4 and IPv6
  - The tracker serves peers with both only IPv4 and only IPv6 connections
  - In order to reach all of peers I want the tracker to pass both my IPv4 and IPv6 address to them but this is only possible if the tracker receives both my IPv4 and IPv6 address no matter which address family the announce of my client goes to

As stated in the opening post, the ipv6 parameter only gets passed for me when binding the client to an IPv6 address. However, as this means the tracker will receive my announce from my IPv6 address, it doesn't seem to serve any purpose in my case.

> Consider the case where you're using a proxy, a VPN or NAT. In either of those cases, passing along your IPv6 address may be a burden to the swarms (if nobody can connect to you) to an information leak that you may not want.
I may be lacking knowledge about something but:
In case I'm using a proxy, chances are I'm not going to be connectable to other peers at all.
If using a dual-stack VPN, I'm probably only going to be connectable through its IPv6 address (which to my understanding should be the preferred address to announce then). The same applies to NAT except I'm more likely to be connectable through both v4 and v6 in that case if configured properly.

**Comment by arvidn** [comment]
> In order to reach all peers I want the tracker to pass both my IPv4 and IPv6 address to them but this is only possible if the tracker receives both my IPv4 and IPv6 address no matter which address family the announce of my client goes to

Normally the way it works is that trackers look at the source IP of the announce and use that. So, as long as your client announce to the tracker over both IPv4 and IPv6 (i.e. two separate announce requests) the tracker *is supposed to* record both of your IPs.

Do you see two separate announces to the tracker? if so, are the over separate address families?

**Comment by lovesyk** [comment]
No, I only see one announce for a random address family. Depending on that, the tracker receives only my IPv4 or IPv6 address.

If the client is supposed to send both announcements, does this result in Deluge being the culprit? Or maybe an incompatibility with recent libtorrent versions considering the tracker did receive both addresses on an older Deluge + libtorrent 0.16.18 in some way (although I don't know whether it's by appending ip/ipv6 parameters or doing multiple announcements)?

**Comment by arvidn** [comment]
There is a test that covers exactly this case, that asserts that a tracker whose name resolves to both an IPv4 and IPv6 address will be announce to twice, once for each address family.
The test is here: https://github.com/arvidn/libtorrent/blob/RC_1_1/simulation/test_tracker.cpp#L290

The specific settings being tested are largely defined by the ``settings()`` function (called [here](https://github.com/arvidn/libtorrent/blob/RC_1_1/simulation/test_tracker.cpp#L337)). Defined [here](https://github.com/arvidn/libtorrent/blob/RC_1_1/test/settings.cpp#L39).

**Comment by lovesyk** [comment]
I tried changing my settings to match settings.cpp but that didn't affect anything. Only my IPv6 address got announced to the IPv6 tracker address.

In case you wanted me to actually run this test I unfortunately don't know how to do that.

I also tested the working Deluge version 1.3.10 with libtorrent 0.16.18.0. It seems to also send one announce but always includes both ip and ipv6 parameters (which I suppose is not a recommended approach as it was removed?).

**Comment by arvidn** [comment]
and the tracker in question resolves to at least one IPv4 and one IPv6 address? or does the .torrent file contain multiple tracker entries, one for each address family?

1.0 does not have as good support for IPv6 (and in fact @ssiloti significantly improved it more in master).

Looking at the code in ``RC_1_1``, it looks like supporting both address families simultaneously requires you to set the ``listen_interfaces`` setting to an empty string. This has been greatly improved (and simplified) in master. Could you try that? not setting any specific listen interface?

**Comment by lovesyk** [comment]
Yes, the tracker hostname resolves to two IPv4 and two IPv6 addresses. No, there is only one entry in the tracker list.

I compiled master but it doesn't seem to be compatible with the latest Deluge version. I receive the following message on startup:
`[ERROR   ] 23:24:06 main:248 'module' object has no attribute 'session_settings'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/main.py", line 241, in start_daemon
    Daemon(options, args)
  File "/usr/lib/python2.7/dist-packages/deluge/core/daemon.py", line 147, in __init__
    read_only_config_keys=read_only_config_keys)
  File "/usr/lib/python2.7/dist-packages/deluge/core/core.py", line 106, in __init__
    self.settings = lt.session_settings()
AttributeError: 'module' object has no attribute 'session_settings'`

An issue with the interfaces seems likely considering the "ipv6" parameter only gets set when explicitly listening on an IPv6 address as opposed to an empty string as described in the first post.

**Comment by arvidn** [comment]
if you only listen to an IPv4 interface, your IPv6 address will not be announced. Similarly, if you only listen to an IPv6 interface, your IPv4 address won't be announced. If you set the ``listen_interfaces`` to an empty string, libtorrent is supposed to listen on all interfaces, which should also make it announce to both IPv4 and IPv6 (assuming you have interfaces for both).

weird about that error. Please make sure the python binding and the libtorrent library match! If you just update one, they won't be compatible. (i.e. that's ``libtorrent.so`` in the python module directory and ``libtorrent-rasterbar.so`` in ``/usr/local/bin``, or wherever it's installed)

**Comment by lovesyk** [comment]
I did update the python bindings as well and now also double-checked the .so files are actually being updated.

I noticed the `libtorrent-rasterbar.so` has its version number appended on Debian which apparently got bumped to 10.0.0. I tried adding a symlink from 9 but that didn't change anything.

As the build requires a `build-aux` directory I copied it from the 1.1.4 release as I'm not sure where it is/was coming from. Not sure if this is related to the issue.

**Comment by arvidn** [comment]
is there a way for you to tell exactly what the ``listen_interfaces`` setting get set to for you? I'm working on extending that test, and there may be some cases that aren't working correctly. It seems that if you listen on 0.0.0.0 (and port) or 0.0.0.0 and ::0 it works. If you listen on a specific IP address, it doesn't seem to work.

**Comment by lovesyk** [comment]
It being empty (unless stated otherwise in my posts) is the only thing I can say. `listen_interfaces` does unfortunately not appear in the ltConfig plugin for me to be able to see its actual value.

I did some listening experiments:
  - 0.0.0.0 behaves the same as an empty string (listening on all address families, one announcement to random family, no ipv6 parameter at any time)
  - ::0 behaves almost same as listening to my IPv6 address (listening only on IPv6, one announcement to the IPv6 tracker address) with the exception that the ipv6 parameter will not be send in the announcement

Also, one correction about the opening post: Apparently I didn't test the pre-compiled Ubuntu binaries as their libtorrent failed to install because of unmet dependencies. Their repository includes version 1.0.11.0 which seems to work as currently intended:
  - one IPv4 announcement (+ ipv6 parameter on private torrents)
  - one extra IPv6 announcement including ipv6 parameter on private torrents
So it seems to be some regression most likely related to `listen_interfaces`.

**Comment by arvidn** [comment]
I would guess ltConfig omits the ``listen_interfaces`` setting because the regular settings already configure it. It's important that each interface/IP includes a listen port though. If not, parsing will fail and that interface will be ignored. But I suppose there is deluge logic between the string you specify and the actual libtorrent setting.

**Comment by arvidn** [comment]
here's a fix to make this work correctly when binding to specific IPs. https://github.com/arvidn/libtorrent/pull/2258

**Comment by lovesyk** [comment]
As in multiple specific IPs for both IPv4 and IPv6? Don't think this is possible to set through Deluge but nice nevertheless.

I'll spend some more time trying to make master work with Deluge if you say there's not supposed to be any incompatibility.

**Comment by arvidn** [comment]
right. Also a single specific IPv4 address will prevent accepting connections over IPv6 (0.0.0.0/INADDR_ANY is an exception that will accept from all interfaces).

There may be some incompatibilities with master, but I would definitely expect ``session_settings`` to still be there. To me that error message sounds like the module failed to be loaded/imported in the first place.

**Comment by the8472** [comment]
At least [BEP15](http://bittorrent.org/beps/bep_0015.html#ipv6) hints at the option to announce on both address families. We probably should add that to BEP7 too.

**Comment by lovesyk** [comment]
It doesn't seem like I'll be able to get master working. No matter if updating the sources of Debian's package or compiling according to the github instructions, I always end up with those same Python errors. Guess I'll stay at 0.16.18.0 / 1.0.11.0 until there is some prepackaged version for Debian...


But assuming master works just as 1.0.11.0 with the improvements to `listen_interfaces`, is there any chance to get a setting to get back the earlier behavior of announcing both address families, no matter whether it's a private torrent or not?

In my case I'm not concerned with any kind of IP leakage at all, I simply want to reach as many peers as possible and currently only 0.16.18.0 out of the versions I've tested gives me that behavior.

**Comment by arvidn** [comment]
no, there's no setting to revert that logic. However, I was under the impression you were using libtorrent 1.1.x (you said 1.1.4 at the initial post). If you are using 1.1.4 there are two options:

1. make sure Deluge ends up configuring the listen interface as "0.0.0.0:<listen-port>".

2. build and install libtorrent ``RC_1_1`` branch (which is soon to become 1.1.5)

**Comment by lovesyk** [comment]
> no, there's no setting to revert that logic
Which is why I asked if there's any chance to get one implemented. With dedicated IPv4 addresses thinning out for private connections I don't see the current approach being future-proof.

> I was under the impression you were using libtorrent 1.1.x (you said 1.1.4 at the initial post)
Yes, I was always talking about 1.1.4 unless stated otherwise. 0.16.18.0 and 1.0.11.0 were the two versions I tested which worked better than 1.1.4 so if I have to revert, it'll be to one of them.

> make sure Deluge ends up configuring the listen interface as "0.0.0.0:listen-port".
As there is no way for me to make sure Deluge sets this very string and entering "0.0.0.0" doesn't change anything in Deluge compared to an empty string, this won't work.

> build and install libtorrent RC_1_1 branch (which is soon to become 1.1.5)
I tried compiling RC_1_1 but ended up with the same non-working result as with master. Just to point out: Debian comes with 1.1.1 and I successfully updated that to 1.1.4 so there seems to be an extra step required in making RC_1_1 / master work.

**Comment by arvidn** [comment]
> With dedicated IPv4 addresses thinning out for private connections I don't see the current approach being future-proof.

by "current approach" you mean announcing to the tracker once for every listen interface/IP, right?
In what way is that not future proof?

> As there is no way for me to make sure Deluge sets this very string and entering "0.0.0.0" doesn't change anything in Deluge compared to an empty string, this doesn't seem to be an option.

Seems like there may be a bug in deluge then. In fact, looking at how deluge sets this value, it looks like it's not comma separating the interfaces. I would suggest you make sure you're only configuring a single listen port with deluge, to try to avoid this issue.

https://github.com/deluge-torrent/deluge/blob/e3abdf99015806a4078a946aef1294efd60eb6af/deluge/core/preferencesmanager.py#L208

**Comment by lovesyk** [comment]
> by "current approach" you mean announcing to the tracker once for every listen interface/IP, right?
No, I meant only announcing on IPv6 interfaces for torrents marked as private. At least that's what's happening to me on 1.0.11.0.

> I would suggest you make sure you're only configuring a single listen port with deluge, to try to avoid this issue.
I've always only configured one port so there seems to be yet another issue somewhere.

**Comment by arvidn** [comment]
> No, I meant only announcing on IPv6 interfaces for torrents marked as private. At least that's what's happening to me on 1.0.11.0.

I see. multi-homed support has developed gradually, and back in the 1.0.x days I don't think it was very robust.

> I've always only configured one port so there seems to be yet another issue somewhere.

It's possible deluge allocates a range of ports starting at the one you specify. Historically that was the interface to libtorrent, to specify back-up ports. There was at least one path where deluge definitely constructed a correct listen_interfaces string, when using a random listen port.

Anyway, as I've looked into this more now, I feel confident that this is an issue in Deluge.

**Comment by lovesyk** [comment]
> I see. multi-homed support has developed gradually, and back in the 1.0.x days I don't think it was very robust.

So the behavior I noticed with 1.0.11.0 was not intended and currently libtorrent is supposed to announce both address families in every case? That would be great.

> There was at least one path where deluge definitely constructed a correct listen_interfaces string, when using a random listen port.
I tried setting a random port with 0.0.0.0 as the interface but didn't notice any difference either.

I will try compiling qBittorrent with a recent libtorrent version to see how it behaves compared to Deluge a bit later.

**Comment by arvidn** [comment]
> So the behavior I noticed with 1.0.11.0 was not intended and currently libtorrent is supposed to announce both address families in every case? That would be great.

Yes, the current intended behavior is to announce for each listen interface (master). In current stable (I think RC_1_0 and RC_1_1) it attempts to announce once to each *address family* that's being listened on, which isn't quite right, but works in most real-world setups.

**Comment by lovesyk** [comment]
I compiled qBittorrent 3.3.15 with libtorrent 1.1.4 and saw the same behavior as with Deluge when not specifying any network interface. Setting `Connection\Interface=0.0.0.0` didn't change anything either.

After that, I tried compiling it with RC_1_1 but received
> ../../src/base/bittorrent/infohash.cpp: In constructor 'BitTorrent::InfoHash::InfoHash(const sha1_hash&)':
> ../../src/base/bittorrent/infohash.cpp:43:43: error: invalid operands of types 'std::size_t() {aka long > > > > unsigned int()}' and 'int' to binary 'operator*'
>      char out[(libtorrent::sha1_hash::size * 2) + 1];
>                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
> ../../src/base/bittorrent/infohash.cpp:44:5: error: 'to_hex' is not a member of 'libtorrent'
>      libtorrent::to_hex((char const*)&m_nativeHash[0], libtorrent::sha1_hash::size, out);
>      ^~~~~~~~~~
> ../../src/base/bittorrent/infohash.cpp:44:84: error: 'out' was not declared in this scope
>      libtorrent::to_hex((char const*)&m_nativeHash[0], libtorrent::sha1_hash::size, out);
>                                                                                     ^~~
> ../../src/base/bittorrent/infohash.cpp: In constructor 'BitTorrent::InfoHash::InfoHash(const QString&)':
> ../../src/base/bittorrent/infohash.cpp:54:19: error: 'from_hex' is not a member of 'libtorrent'
>          m_valid = libtorrent::from_hex(raw.constData(), 40, (char*)&m_nativeHash[0]);
>                    ^~~~~~~~~~

So the issues don't seem to be limited to Deluge.

**Comment by arvidn** [comment]
would it be possible for you to post the alert log you get in a run experiencing the problem (i.e. only one interface announce to the tracker, instead of both)?

**Comment by lovesyk** [comment]
So apparently qBittorrent actually requires an interface name instead of an address in `Connection\Interface`. I tried entering my interface name but this resulted in it only listening on IPv4.

As I don't have a GUI on the machine I hope the "execution log" is the same thing:
> (N) 2017-08-24T16:20:51 - qBittorrent v3.3.15 started
> (N) 2017-08-24T16:20:51 - qBittorrent v3.3.15 started
> (N) 2017-08-24T16:20:51 - qBittorrent v3.3.15 started
> (N) 2017-08-24T16:20:51 - qBittorrent v3.3.15 started
> (I) 2017-08-24T16:20:51 - qBittorrent is trying to listen on any interface port: 8999
> (I) 2017-08-24T16:20:51 - qBittorrent is trying to listen on any interface port: 8999
> (N) 2017-08-24T16:20:51 - Peer ID: -qB33F0-
> (N) 2017-08-24T16:20:51 - Peer ID: -qB33F0-
> (N) 2017-08-24T16:20:51 - HTTP User-Agent is 'qBittorrent/3.3.15'
> (N) 2017-08-24T16:20:51 - HTTP User-Agent is 'qBittorrent/3.3.15'
> (I) 2017-08-24T16:20:51 - DHT support [ON]
> (I) 2017-08-24T16:20:51 - DHT support [ON]
> (I) 2017-08-24T16:20:51 - Local Peer Discovery support [ON]
> (I) 2017-08-24T16:20:51 - Local Peer Discovery support [ON]
> (I) 2017-08-24T16:20:51 - PeX support [ON]
> (I) 2017-08-24T16:20:51 - PeX support [ON]
> (I) 2017-08-24T16:20:51 - Anonymous mode [OFF]
> (I) 2017-08-24T16:20:51 - Anonymous mode [OFF]
> (I) 2017-08-24T16:20:51 - Encryption support [ON]
> (I) 2017-08-24T16:20:51 - Encryption support [ON]
> (I) 2017-08-24T16:20:51 - Embedded Tracker [OFF]
> (I) 2017-08-24T16:20:51 - Embedded Tracker [OFF]
> (I) 2017-08-24T16:20:51 - UPnP / NAT-PMP support [ON]
> (I) 2017-08-24T16:20:51 - UPnP / NAT-PMP support [ON]
> (I) 2017-08-24T16:20:51 - GeoIP database loaded. Type: GeoLite2-Country. Build time: Thu Aug 3 03:44:22 2017.
> (I) 2017-08-24T16:20:51 - GeoIP database loaded. Type: GeoLite2-Country. Build time: Thu Aug 3 03:44:22 2017.
> (N) 2017-08-24T16:20:51 - Web UI: Now listening on port 8081
> (N) 2017-08-24T16:20:51 - Web UI: Now listening on port 8081
> (I) 2017-08-24T16:20:51 - qBittorrent is successfully listening on interface :: port: TCP/8999
> (I) 2017-08-24T16:20:51 - qBittorrent is successfully listening on interface :: port: TCP/8999
> (I) 2017-08-24T16:20:51 - qBittorrent is successfully listening on interface 0.0.0.0 port: TCP/8999
> (I) 2017-08-24T16:20:51 - qBittorrent is successfully listening on interface 0.0.0.0 port: TCP/8999
> (I) 2017-08-24T16:20:51 - qBittorrent is successfully listening on interface 0.0.0.0 port: UDP/8999
> (I) 2017-08-24T16:20:51 - qBittorrent is successfully listening on interface 0.0.0.0 port: UDP/8999
> (N) 2017-08-24T16:20:51 - '[torrent name]' resumed. (fast resume)
> (N) 2017-08-24T16:20:51 - '[torrent name]' resumed. (fast resume)
> (I) 2017-08-24T16:20:51 - External IP: [IPv4]
> (I) 2017-08-24T16:20:51 - External IP: [IPv4]

After that, qBittorrent is listening on both IPv4 and IPv6 but as with Deluge, announces only on one of them.

**Comment by arvidn** [comment]
Thanks for helping out with this. There could be something that isn't working right which the simulator has its own implementation of (making it work there). Something like enumerating the network interfaces.

Would you mind running the same test in Deluge, where you have more control over settings? please set the ``alert_mask`` to 0x7fffffff. This will enable all alerts, including logging. If you could just add a single torrent that exhibits this error, it would be great as having more would make the logging a lot more verbose.

Can Deluge save the alert log to a file? if so, you would want to do that and paste it at pastebin.com or as similar service. Since the log may contain sensitive information, you may want to look it over and possibly redact some parts.

It's also possible that there are some other aspects of your case that isn't covered by the test. Like:

* whether the torrent is private or not (I get the impression it's not)
* whether the tracker is a UDP or HTTP tracker (I think the test only covers HTTP, but from what I gather, you're referring to an HTTP tracker)

**Comment by arvidn** [comment]
@ssiloti since you're multi-homed-savvy, do you have any theories I can test? (ideally in the simulator)

**Comment by lovesyk** [comment]
As requested, here is the log of Deluge with the following configuration:
- Deluge version 1.3.13
- libtorrent version 1.1.4
- one private torrent (my posts have always been about private torrents unless stated otherwise)
- one HTTP tracker
- interface set to 0.0.0.0
- ports set to random

https://pastebin.com/fa7SJURM

**Comment by arvidn** [comment]
thanks! The log seems cut off exactly as it started to get interesting though :) nothing happened after that?
I would expect that after the first ``tracker_reply_alert`` there is another announce. The external IP you're getting from the tracker implies that you first hit the IPv6 one. I wonder if there's an issue where it only re-announces if the first announce is to the IPv4 address.

**Comment by lovesyk** [comment]
If I wait another few minutes, it continues like this: https://pastebin.com/QYN5CY6W
So no, nothing seems to happen after that.

Yes, it usually announces to the IPv6 address but there are also times when it's the IPv4. Another announcement does not happen in that case either.

**Comment by arvidn** [comment]
I just noticed that you don't have log_alerts in your log. I can see how you enable the log alerts. My suspicion is that either deluge filters them and omits them from its log, or libtorrent you're using is specifically built with logging disabled. Specifically the ``TRACKER RESPONSE`` log would be very useful to see.

For instance, you have a single tracker resolving to multiple IPs, right? It's not two separate tracker entries (with different hostnames) that individually resolve to a single address family, right?

**Comment by lovesyk** [comment]
I'm using the default build process of Debian (package of 1.1.1 with the source files replaced by 1.1.4). I tried searching for "log", "tracker" or "response" but didn't see anything that looked like a flag to disable logs. Any specific keyword to look for?

Yes, as I mentioned it's one single tracker:
![tracker](https://user-images.githubusercontent.com/9806747/29995711-3ff295a6-8ff0-11e7-80a5-da5db6b0f48a.png)

**Comment by arvidn** [comment]
all logging can be disabled by a compile time flag to libtorrent. That's probably not the case. I think it's more likely that Deluge only prints specific alerts to its log, and it doesn't print the libtorrent log alerts.

**Comment by lovesyk** [comment]
Just to be sure, I tried qBittorrent's PPA builds (unstable 3.4.0 + libtorrent 1.1.4) but didn't see any difference compared to my builds.

And although unrelated to libtorrent, I've also tried out Transmission 2.92 to see how it behaves and I saw similar issues there as well. It also sends only one announcement to one random address family but appends the "ipv6" parameter in any case which means everything's fine if the tracker resolves to an IPv4 address but if it's IPv6, the tracker won't receive my IPv4.

**Comment by arvidn** [comment]
interesting. one explanation for this behavior would be if the torrent file contained two separate trackers (with separate hostnames) organized in the same *tier*. (trackers in the same tier are treated as load-balancing replicas, and only one of them is contacted). But you've said there's only a single hostname that resolves to both IPv4 and IPv6, so it must be something else.

**Comment by lovesyk** [comment]
It seems weird to me that so many clients seem to be affected. One'd think users being only connectable through IPv6 would notice it as the speeds should by quite a bit lower without any IPv4 peers. Yet I didn't see any still opened bug reports worth noting.

But I don't see this being related to my setup either as I've seen the same behavior throughout Arch and different Debian releases on multiple machines. Which is the reason I've been holding back the upgrade from 0.16.18 for a long time.

**Comment by lovesyk** [comment]
I tried the recently released 1.1.5 with Deluge but didn't notice any change in behavior. There's still only 1 announcement for a random address family regardless of the interface (empty vs. 0.0.0.0) or port settings.
So "fix IPv6 tracker support by performing the second announce in more cases" apparently wasn't the solution to this issue.

**Comment by arvidn** [comment]
I can't reproduce this behavior, nor have I been able to come up with a way for it to happen by inspecting the code. I'm sure there's some specific setting or sequence of calls deluge sets/makes that trigger this behavior. I seem to recall I may have increased logging as well though, could you enable logging and see if it says anything interesting? (it's an alert flag)

**Comment by lovesyk** [comment]
Unfortunately, my knowledge of C++ is too small to effectively help out here...

Here is a log of 1.1.5: https://pastebin.com/A6vvFRFk (no, there is nothing after that for)
As I've seen the same behavior when using qBittorrent, I don't think this is an (exclusively) Deluge issue.

**Comment by lovesyk** [comment]
@arvidn: Do you have any idea if my findings in the previous comment seem to be related to finding the root of the issue? I'll continue searching but only if I'm not completely off-track as it's a bit difficult for me.

**Comment by arvidn** [comment]
thanks for pinging me. I had missed your previous message. I'll look into this some more

**Comment by arvidn** [comment]
it sounds like ``m_ses.get_ipv6_interface().address()`` and ``m_ses.get_ipv4_interface().address()`` both return ``INADDR_ANY``? If so, that suggests that the listen logic failed to bind to specific interfaces.

Which ``listen_succeeded_alert``s do you get in the log? do you see a log for each interface you intended to bind to/listen on?

**Comment by ssiloti** [comment]
@arvidn This is 1.1.5 so binding to `::` is the expected behavior.

**Comment by lovesyk** [comment]
In the log I posted earlier (https://github.com/arvidn/libtorrent/issues/2255#issuecomment-337981993) there are multiple `listen_succeeded_alert` entries. Is it something different you're looking for? It doesn't look like it's binding to anything specific.

**Comment by arvidn** [comment]
the default value for ``listen_interfaces`` in 1.1.5 (afaict) is "0.0.0.0:6881". with this, libtorrent will try to bind to all interfaces, and in the test, it ends up doing so. It gets one v6 and one v4 interface and the logic for re-announcing works as expected. However, if the ``listen_interfaces`` setting is set to explicitly bind to the v6 any address, such as: "[::0]:6881", it will *not* bind to an IPv4 address, and only attempt to announce to the v6 tracker endpoints, not the v4 ones.

I believe (and hope) the situation in master is improved and a bit more intuitive.

**Comment by arvidn** [comment]
I think the fundamental problem is that the variables in the session holding the "canonical" v4 and v6 listen interfaces, treats inaddr_any as unset. in your case, you successfully listens to the inaddr_any addresses, and presumably those get assigned to the variables, but then treated as not set.

**Comment by arvidn** [comment]
please test this patch: https://github.com/arvidn/libtorrent/pull/2500

**Comment by lovesyk** [comment]
With the patch I'm seeing behavior identical to what I described in https://github.com/arvidn/libtorrent/issues/2255#issuecomment-337981993, i.e. two announcements to two random address families with the second announcement containing "port=0" and thus being considered invalid.

**Comment by lovesyk** [comment]
Also, apparently I only missed it and `listen_interfaces` actually is viewable and configurable through ltConfig. The behavior above is with a real setting of "0.0.0.0:port" (empty string in Deluge's settings).
I tried setting a real empty string like you once suggested and (unless it was only by chance) one IPv4 and one IPv6 announcement is sent as expected. However, the issue with the second announcement containing port=0 remains and I obviously can't configure the random port used in this case.

**Comment by arvidn** [comment]
in the log you posted, I only see one announce. It would also help to see debug log output, which should get printed (assuming deluge prints all alerts, not just the ones it knows how to handle) by setting all bits in the ``alert_mask`` setting.

I realized that in the simulator the ``local_endpoint()`` did not return "0.0.0.0" on a listen socket bound to INADDR_ANY, but it seems real sockets do. I updated the simulator (locally) to match that and updated the patch to fix a few issues.

I haven't managed to figure out where ``port=0`` may be coming from though. Afaict, the only place I can find is [here](https://github.com/arvidn/libtorrent/blob/RC_1_1/src/session_impl.cpp#L5495).

would you mind testing the updated PR?

**Comment by lovesyk** [comment]
Unfortunately no change with the updated PR but on the positive side [here](http://sebsauvage.net/paste/?b895f65098cbd9df#5z76q9NcfuXDehcJ2JLHY9/oj9LaDfad1Wv0EoIWhkk=) is finally what should be a full debug log showing two IPv6 announcements (second one with port=0) using 0.0.0.0:port.

Looking at the full logs I've seen yet another issue if using an empty interface string but two issues is probably enough for now. I'll mention it later.

**Comment by arvidn** [comment]
One theory I have is that you enable and disable force_proxy (I know, it's pretty far-fetched) in between the first and second tracker announce. Looking closer at it I found this issue (from session_impl::listen_port()'s point of view).

https://github.com/arvidn/libtorrent/pull/2515

**Comment by arvidn** [comment]
I've updated the patch to add more logging around the listen port. I can't understand how the port can change between those announces. Given that you seem to have figured out how to build and enable logging, would mind giving the update patch a try? thanks!

**Comment by lovesyk** [comment]
Yes, I deleted the Deluge config multiple times and at some point forgot you had to explicitly tell ltConfig to apply the settings on startup which is why `alert_mask` was never actually set.

Now this is weird, with my current build (`ipv6-tracker-announce`+`force_proxy-fix-1.1`) I always see the first announcement being IPv4 and the second IPv6. I'll do some more testing in case it's just by chance but anyway, are those `debug_log`s in https://github.com/arvidn/libtorrent/pull/2500/commits/65ee9cfe3bac917b9167a09023579b2a2e32c1ed really correct? It wouldn't build for me so I changed them to `session_log`s.
Here's the [current log](http://sebsauvage.net/paste/?c3de6937def703a7#AdQy84nsQ9BXXoFTGAbMNTlqzqeC2dr/XBWCrAH0pt8=).

**Comment by arvidn** [comment]
yes, that was a typo. I was a bit trigger happy on the push there. i also made a mistake in one of the logs, not actually printing the value. So, it looks like the listen sockets aren't removed, the 0 seems to consistently come from the ``external_port`` field in the first listen socket object.

It's unclear why it gets set to zero though. I've added a bit more logging (and fixed the issues in the previous patch). I'll think about what other logging I can add to narrow this down further. i haven't found an explanation for the ``external_port`` becoming zero. I added logs when it's updated and there were logs already when the listen sockets are removed and re-opened. You'd log suggests that none of those things happen.

**Comment by lovesyk** [comment]
And here's the [updated log](http://sebsauvage.net/paste/?d175e675024e7500#yevVwBstBwTtUX0kc7bLVbqgLaouHIDAJ2m9K2x0Sqs=) although I suppose it doesn't tell anything new.

**Comment by arvidn** [comment]
thanks! I'm pretty sure I figured it out. the reason I couldn't reproduce it in the simulator is because it doesn't support openssl, and this only happens when building with openssl enabled.

i've updated the PR and at some point I will squash and merge it. Please test it if you have a chance!

**Comment by lovesyk** [comment]
Great, both a correct IPv4 and IPv6 announcement are now being sent with default Deluge settings. Thank you for the long debugging session!

Unfortunately, the tracker I primarily wanted to have this issue solved for doesn't seem to like it this way. It is the same one mentioned in https://github.com/arvidn/libtorrent/issues/219 which definitely wasn't solved back then as I've talked to @Lenmaer before opening this issue.
NexusPHP doesn't seem to accept two announcements and requires only one containing both addresses which I've come to understand is not desirable behavior. I'm not sure how widespread such trackers are but it seems they won't work without workarounds.
With the proper 2 announcements, NexusPHP will recognize only an IPv6 address for my client as it receives that one last. Is this guaranteeed behavior (it's always been that way for me since the last few builds)?
If it is, setting `announce_ip` to my external IPv4 address should provide an ugly but working workaround (and yes, setting it results in the tracker announcing both of my addresses) unless you have any better idea...

**Comment by arvidn** [comment]
Do you know how the tracker ties the two announces back to the same client? Is this a private tracker that uses a key tied to your user in the URL?

**Comment by lovesyk** [comment]
Yes, it's a private tracker that appends a key to the tracker URL. I'm assuming a new announcement simply overwrites previous ones with the same key.

**Comment by arvidn** [comment]
I guess this raises some other questions as well. for instance, the ``event=completed`` announce should only be sent to one of the IPs. In the case of private trackers, they presumably would get confused if you send the same ``uploaded`` and ``downloaded`` from separate IPs as well.

**Comment by lovesyk** [comment]
I finished downloading a file with the new build while having `announce_ip` set and the tracker counted my download amount correctly. I suppose it makes sense if all it's doing is overwriting previous announcements based on the key.
Isn't there a specification of some sort to handle all those cases?

**Comment by arvidn** [comment]
in my experience there has been very little (if any) involvement in protocol extensions or specifications from anyone in the private tracker-community. The specifications that exist mostly don't consider the case of private torrents and the impact of wanting to attribute transfers to a certain identity.

**Comment by arvidn** [comment]
One thing that occur to me, there is the tracker key (``&key=``) which is used to identify a user/session for the duration of announcing to the tracker(s). This is intended to be used for clients changing IP. Announcing once over IPv4 and once over IPv6, using the same tracker key, legitimately makes the tracker thing you changed IP, and should replace the previous one.

This isn't a case that's received a lot of thought in libtorrent. It's not trivial. On the one hand you would want the key to persist as you fail over to another tracker in the same tier. On the other hand, you would want each source interface to have its own key as well, to avoid the v6 announce replacing the v4 announce.

On the other hand, it becomes tricky to account downloads, uploads and corrupt pieces if a single download announce under multiple keys. I'm leaning towards using multiple keys though, as the purpose of the ``&key=`` parameter is to support the client changing IP, which should be assigned to a source interface.

To avoid unnecessary privacy leaks, keys should not be shared across torrents, which would suggest that torrents should have a list of keys, on for each source interface (that we accept connections on and announce through).

@ssiloti and @the8472 do you have any thoughts on this?

**Comment by arvidn** [comment]
@lovesyk btw, for private torrents, if you disable ``anonymous_mode``, the ``&ipv6=`` parameter *is* sent in announces.

**Comment by lovesyk** [comment]
Another issue is simply the tracker software involved. NexusPHP in this case hasn't been updated for many years and even if you specify how trackers are supposed to behave, it's not like the tracker administrators are going to patch or replace it. Especially considering most clients seem to simply append ip(v4|v6)* parameters randomly.

The `ipv6` parameter only gets appended for me if I bind to a specific IPv6 address which pretty much makes it useless. Though even if it worked, the first announcement coming from my IPv4 would get overridden by the IPv6 one anyway.

**Comment by the8472** [comment]
> On the other hand, it becomes tricky to account downloads, uploads and corrupt pieces if a single download announce under multiple keys. I'm leaning towards using multiple keys though, as the purpose of the &key= parameter is to support the client changing IP, which should be assigned to a source interface.

Yes, that is the accurate but also the most complex solution. For opentracker it is fine to use the key across ipv4 and ipv6 because it keeps separate v4 and v6 lists and thus doesn't evict across address families, which is exactly what everyone *should* be doing. Alas, theory and practice...

If we want a cheap hack solution we could just space the announces in time and let them overwrite each other so all addresses will be visible over time. Or we could select different strategies for private and public torrents.

**Comment by ssiloti** [comment]
We could create separate keys for each listen interface easily enough. The `listen_interface_t` instances have stable addresses so we could append the pointer value to the initial key and hash that to generate per-interface keys.

**Comment by the8472** [comment]
There are several things a tracker might use for identity tracking:

* passkey (part of announce URL)
* key
* tracker id
* peer id
* IP address

**Comment by arvidn** [comment]
In the general case (which libtorrent master mostly supports), a client might as well have two IPv4 connections, or two IPv6 connections (i.e. not just one v4 and one v6). So I think keys should be assigned to interface and not address family.

**Comment by arvidn** [comment]
the announce issue was fixed in RC_1_1 and the tracker key-issue was addressed in master.
