### ISSUE TITLE
libtorrent-rasterbar-1.2.1 install fail !

### ISSUE THREAD

**Issue by nikolamakin** [arvidn/libtorrent#3948]
```
libtorrent-rasterbar-1.2.1
=============================================================
Build options:
  deprecated functions: yes
  debug build:          no
  invariant checks:     no
  logging support:      yes

Features:
  encryption support:   yes
  dht support:          yes

Extra builds:
  examples:             no
  tests:                no
  python bindings:      no

Pthread library:
  CFlags:               -lpthread
  Libs:                 -lpthread 

Boost libraries:
  version:              
  CPPFlags:             -I/usr/local/include
  LDFlags:              -L/usr/local/lib
  boost.system:         -lboost_system

External libraries:
  system libiconv:      no

OpenSSL library:
  OpenSSL Libs:         -lssl -lcrypto  
  OpenSSL LDFlags:       
  OpenSSL Includes:      

Type 'make' to compile libtorrent-rasterbar 1.2.1
or type 'make V=1' for verbose compiling
and then 'make install' to install it into /server/libtorrent

[root@AY140313212008Z libtorrent-rasterbar-1.2.1]# make
Making all in include/libtorrent
make[1]: Entering directory `/home/libtorrent-rasterbar-1.2.1/include/libtorrent'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/libtorrent-rasterbar-1.2.1/include/libtorrent'
Making all in src
make[1]: Entering directory `/home/libtorrent-rasterbar-1.2.1/src'
  CXX      libtorrent_rasterbar_la-web_connection_base.lo
In file included from ../include/libtorrent/entry.hpp:76:0,
                 from ../include/libtorrent/settings_pack.hpp:36,
                 from ../include/libtorrent/aux_/session_settings.hpp:37,
                 from ../include/libtorrent/peer_connection.hpp:53,
                 from ../include/libtorrent/web_connection_base.hpp:42,
                 from web_connection_base.cpp:38:
../include/libtorrent/string_view.hpp:60:24: error: missing space between ‘""’ and suffix identifier
  constexpr string_view operator""_sv(char const* str, std::size_t len)
                        ^
In file included from ../include/libtorrent/aux_/session_settings.hpp:37:0,
                 from ../include/libtorrent/peer_connection.hpp:53,
                 from ../include/libtorrent/web_connection_base.hpp:42,
                 from web_connection_base.cpp:38:
../include/libtorrent/settings_pack.hpp:93:18: error: function ‘libtorrent::settings_pack& libtorrent::settings_pack::operator=(libtorrent::settings_pack&&)’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘libtorrent::settings_pack& libtorrent::settings_pack::operator=(libtorrent::settings_pack&&)’
   settings_pack& operator=(settings_pack&&) noexcept = default;
                  ^
In file included from ../include/libtorrent/torrent_info.hpp:52:0,
                 from ../include/libtorrent/torrent.hpp:48,
                 from ../include/libtorrent/web_connection_base.hpp:43,
                 from web_connection_base.cpp:38:
../include/libtorrent/file_storage.hpp:65:15: error: function ‘libtorrent::file_entry& libtorrent::file_entry::operator=(libtorrent::file_entry&&) &’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘libtorrent::file_entry& libtorrent::file_entry::operator=(libtorrent::file_entry&&)’
   file_entry& operator=(file_entry&&) & noexcept = default;
               ^
make[1]: *** [libtorrent_rasterbar_la-web_connection_base.lo] Error 1
make[1]: Leaving directory `/home/libtorrent-rasterbar-1.2.1/src'
make: *** [all-recursive] Error 1
[root@AY140313212008Z libtorrent-rasterbar-1.2.1]#
==============================================================
```
so .whats the fuck . how installed ?
document is fail !
we can do it installation easier !!

**Comment by arvidn** [comment]
which compiler and compiler version are you using?

**Comment by arvidn** [comment]
I have not come across a compiler that enforce this. but here's (what I believe) is a fix: https://github.com/arvidn/libtorrent/pull/3949

**Comment by filips123** [comment]
I have similar error. I'm trying to automatically build and publish Python bindings for libtorrent as wheels using GitHub Actions and cibuildwheel (for #4218). My code is [here](https://github.com/filips123/libtorrent/tree/build-python-bindings-test) (I will push it to PR branch once it is ready): I changed some things in `bindings/python/setup.py`, Boost installation is in `bindings/python/tools/install_boost.sh` and main workflow file is in `.github/workflows/python.yml`.

It works for me on Ubuntu using GCC 9.3. Wheel build successfully and seems to work with `bindings/python/test/test.py`. I have this GCC version:

```bash
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-10ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)
```

However, Boost.Python and some other libraries are not statically linked. This means that users who don't have Boost.Python installed won't be able to use wheel. It is also not built using `manylinux` image, which can cause problems for users of other distributions. Because of this I use cibuildwheel which will automatically build wheels for Windows, macOS and Linux using `manylinux` Docker images. Then it should also detect non-statically-linked libraries and include them.

However, I have problems. Windows and macOS builds are currently failing, but for other reasons (on Windows I don't have Boost in include path, on macOS it will [try to link Boost for Python 3.7](https://github.com/filips123/libtorrent/runs/953568193?check_suite_focus=true#step:6:674) even if I'm trying to build it for Python 3.5).

On Linux, it fails with ([CI output](https://github.com/filips123/libtorrent/runs/953568088?check_suite_focus=true#step:6:682)):

```
  ../../src/add_torrent_params.cpp:41:22: error: function ‘libtorrent::add_torrent_params& libtorrent::add_torrent_params::operator=(libtorrent::add_torrent_params&&) &’ defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ‘’
    add_torrent_params& add_torrent_params::operator=(add_torrent_params&&) & noexcept = default;
                        ^~~~~~~~~~~~~~~~~~
  
      "g++"  -ftemplate-depth-512 -std=c++17 -pthread -Os -finline-functions -Wno-inline -Wall -Wno-c++11-compat -fvisibility-inlines-hidden -Wall -Wextra -Wno-format-zero-length -Wno-noexcept-type -Wparentheses -Wpedantic -Wvla -fPIC -fvisibility=hidden -DBOOST_ALL_NO_LIB -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_HAS_STD_CHRONO -DBOOST_ASIO_NO_DEPRECATED -DBOOST_JSON_HEADER_ONLY -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_NO_DEPRECATED -DBOOST_SYSTEM_NO_DEPRECATED -DNDEBUG -DTORRENT_BUILDING_LIBRARY -DTORRENT_USE_I2P=1 -DTORRENT_USE_RTC=0 -DUSE_GNUTLS=0 -D_FILE_OFFSET_BITS=64 -D_SILENCE_CXX17_ALLOCATOR_VOID_DEPRECATION_WARNING -D_WIN32_WINNT=0x0600  -I"../../deps/json/include" -I"../../deps/try_signal" -I"../../include" -I"../../include/libtorrent" -I"/usr/local/include" -I"/usr/local/opt/boost/include" -I"/usr/sfw/include" -c -o "../../bin/783fceb1a71c45c2cdda5122f5c0e448/src/add_torrent_params.o" "../../src/add_torrent_params.cpp"
```

I tried to run the same command locally, both in latest Ubuntu and `manylinux2010` (`quay.io/pypa/manylinux2010_x86_64:2020-05-20-c7bbd11`) images. On Ubuntu, it works normally, but on `manylinux2010`, it also fails for the same reason. I think the problem might be that `manylinux2010` uses [older versions](https://www.python.org/dev/peps/pep-0571/#the-manylinux2010-policy) of GCC and other libraries to ensure compatibility, but libtorrent does not support that old versions. GCC version on `manylinux2010` is:

```bash
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-8/root/usr --mandir=/opt/rh/devtoolset-8/root/usr/share/man --infodir=/opt/rh/devtoolset-8/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-8.3.1-20190311/obj-x86_64-redhat-linux/isl-install --disable-libmpx --with-mpc=/builddir/build/BUILD/gcc-8.3.1-20190311/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)
```

Is it possible to fix this?

**Comment by arvidn** [comment]
> defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification

What that means is that there are members (in this case, from the standard library) in `add_torrent_params` that do not have nothrow `operator=`. This makes this code sensitive to what the standard library implements.

This was fixed a long time ago, and if you try a newer version of the library, say 1.2.7 or the newly released 1.2.8, you won't have this problem.

**Comment by arvidn** [comment]
the title of this ticket mentions 1.2.1, so I assumed that's what you're using too, but I realise you didn't say which version. The error message suggests that it's a version from a few years ago though. The `add_torrent_params::operator=` has not been declared `noexcept` since May 2017 as far as I can tell.

**Comment by arvidn** [comment]
ah, you're building libtorrent-2.0. It seems like your branch is missing at least this commit from `RC_2_0`:

```
commit b48acbb620d5009eca1c821d08518216081f9219
Author: arvidn <arvid@libtorrent.org>
Date:   Sat Jun 27 16:30:52 2020 +0200

    fix some c++17 that made it in

diff --git a/include/libtorrent/add_torrent_params.hpp b/include/libtorrent/add_torrent_params.hpp
index b7d875495..e40d123f0 100644
--- a/include/libtorrent/add_torrent_params.hpp
+++ b/include/libtorrent/add_torrent_params.hpp
@@ -91,7 +91,7 @@ TORRENT_VERSION_NAMESPACE_2
                add_torrent_params();
                ~add_torrent_params();
                add_torrent_params(add_torrent_params&&) noexcept;
-               add_torrent_params& operator=(add_torrent_params&&) & noexcept;
+               add_torrent_params& operator=(add_torrent_params&&) &;
                add_torrent_params(add_torrent_params const&);
                add_torrent_params& operator=(add_torrent_params const&) &;

diff --git a/src/add_torrent_params.cpp b/src/add_torrent_params.cpp
index a06c086e7..14d46da9e 100644
--- a/src/add_torrent_params.cpp
+++ b/src/add_torrent_params.cpp
@@ -38,7 +38,7 @@ namespace libtorrent {
        add_torrent_params::add_torrent_params() = default;
        add_torrent_params::~add_torrent_params() = default;
        add_torrent_params::add_torrent_params(add_torrent_params&&) noexcept = default;
-       add_torrent_params& add_torrent_params::operator=(add_torrent_params&&) & noexcept = default;
+       add_torrent_params& add_torrent_params::operator=(add_torrent_params&&) & = default;
        add_torrent_params::add_torrent_params(add_torrent_params const&) = default;
        add_torrent_params& add_torrent_params::operator=(add_torrent_params const&) & = default;
```

If you rebase your changes on top of current `RC_2_0`, I would expect this to work. (and please let me know if you run into any other issues)

**Comment by filips123** [comment]
Thanks. I still have some issues but I think I know how to fix them.

Which branch should I then target for PR? `master`, `RC_2_0` or `RC_1_2`? I am currently using `master` and rebased it few days ago.

**Comment by arvidn** [comment]
I think `RC_2_0` is reasonable.
