### ISSUE TITLE
Improvement/bug : Having a choice of announcing to tracker only in ipv4, or v6

### ISSUE THREAD

**Issue by Rootax** [arvidn/libtorrent#4212]
**Please provide the following information**

libtorrent version (or branch):

1.2.x

platform/architecture:

Windows in my cas

compiler and compiler version:
N/A

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

HI.

So, first, sorry for my english, I'll try my best.

It seems to me that since 1.2.x, libtorrent has multiple local endpoints from which an announce is attempted. I believe it's what announce_entry.cpp is showing with line 50-51. It's trying to announce from each tcp addresses. Which in some case would be 1 local ipv4 address, but in some cases 1 local ipv6 address (local link is detected by libtorrent) and the public ipv6 address.

So, for each tracker/torrent, you will have multiples announces, with a different states, like ipv4 "isworking" , but ipv6 can be not working if the tracker doesn't support it. But my guess is, if the tracker doesn't support ipv6 (for announcing), then the local link ipv6 address and the public ipv6 address will non stop try reannouncing, with the timing defined by the lines 100-111.

Am I right ? If so, It can be a problem with some trackers, mostly private. With libtorrent 1.2.x, I noticed that I had a lot of "rate limit reached" from the tracker (or something with the same sense) when I had ipv6 enabled in my torrent client. And it's a kind of a snowball effect since it will try in ipv4 AND v6 when this situation happens. When I chose ipv4 only, and let sometime pass, no warning from the tracker anymore.

Under libt 1.1.x, even with ipv6 enabled (it was listening on all interface), I didn't have this problem.

I don't know if my point is clear ?

In a perfect world, I'll like to have the choice of still listening in v4 and v6, but announcing to tracker only from v4. Aaaaaannnnnnd I'm not good enough to change the code myself :/

I hope what I wrote is understandable : )

Have a nice day.

EDIT : I did another test by only enabling ipv6 on libtorrent 1.2.3. If i choose the correct public address, all the trackers are in "non working" state. While in libtorrent 1.1.x, it's ok. So maybe the problem lies in the way of ipv6 is working with libtorrent 1.2.3 vs 1.1.x... Sorry for the huge post,

**Comment by arvidn** [comment]
I'm not entirely sure I understand what the problem is. It sounds like you end up announcing more often than the tracker allows. This is caused by having multiple listen interfaces, each trying to announce to the tracker. Is that right?

If you listen on IPv6, and the tracker doesn't resolve to an IPv6 address, that interface won't announce to the tracker though, right?

I believe this should be fixed by:
 * each listen interface should also have a netmask associated with it
  * only add `announce_endpoint` announce if the tracker's IP address falls in the range routable by that interface.

This should prevent the loopback interface from announcing to normal trackers for instance (as long as the tracker isn't running on loopback).

It should also improve the SOCKS5 situation, as interfaces that don't route to the socks proxy also could be disabled.

@ssiloti Does this sound reasonable? I'm thinking that if I teach `listen_socket_t` which IP range it "routes" to, they can replace the outgoing sockets as well.

**Comment by arvidn** [comment]
in fact, I'm not sure the way 0.0.0.0 and :: are expanded to all interfaces is the best either.
if one is configured to listen to 0.0.0.0, I think the behavior should be to *only* accept incoming connections from the default route. For example, when starting a VPN as another interface, it will be the highest priority route. Surely it doesn't make sense to *also* use the original, underlying, interface in addition to the `tun0` interface.

**Comment by ssiloti** [comment]
@arvidn It's not clear to me how those netmasks would be assigned.

For IPv6 we already require the tracker and listen addresss to have the same scope ID. This prevents things like link-local addresses being announced to global trackers.

**Comment by arvidn** [comment]
yeah, it's not a fully formed thought yet. I'm imagining somehow associating IP ranges to `listen_socket_t`, such that the loopback listen socket only is "enabled" for addresses falling in the range 127.0.0.0/8. Thinking about this though, I'm not sure this is possible. But I think it's important to, somehow, not announce to trackers via the loopback device (i.e. the `announce_endpoint` for loopback). I'm not sure what the best way to do that is though.

The scenarios I have in mind that I would like to solve are:

(1) don't announce loopback to a non-local tracker
(2) by default, don't bind to the non VPN interface when a VPN is active (this happens today with IPv6)
(3) don't connect to SOCKS5 proxies for endpoints that would not receive packets from the same network the proxy is on (like loopback or a different address family).

**Comment by arvidn** [comment]
@Rootax Do you have a log illustrating the problem you're having? I cannot reproduce the issue of opening a listen socket on loopback and then announcing it to the tracker.

**Comment by arvidn** [comment]
So, from my list of 3 things:

I cannot reproduce (1). I'm interested in more feedback on how to reproduce that.

(2) happens, but only for IPv6, it's justified by the multi-homed DHT support. I'm tempted to by default, maybe not support multi-homed IPv6, but allow binding to "::". The idea being that to enable multi-homed support one would explicitly listen on the interfaces.

(3) is partially addressed by https://github.com/arvidn/libtorrent/pull/4209

**Comment by arvidn** [comment]
@Rootax does this mitigate the problem you experience? https://github.com/arvidn/libtorrent/pull/4213

**Comment by Rootax** [comment]
Hi, thx for all the answers. I don't have logs, but I can take wireshark capture and isolate the relevant data. I could rebuild a version with #4213 , but you said "oh, announce_endpoint is public, this would break ABI". Should I try it anyway ?

To answer to the most important question imo "If you listen on IPv6, and the tracker doesn't resolve to an IPv6 address, that interface won't announce to the tracker though, right?" => Yes it's trying the reannounce. The tracker status is "not working", but without a notion of "oh, I can't even resolve the dns into a v6 address, so I shouldn't even try in ipv6 again." Now, in this case, I wonder how a tracker can tell me I've reach a rate limit, since no data could access the tracker... Maybe if one local endpoint is not in a "is working" state, then it reannounce for all endpoints, and not only the "not working" ones ?

When ipv6 was enabled and working in libtorrent 1.1.x, how was this working ?

Maybe than can be a part of a better behaviour, test if the resolved address is v4 or v6, and if the lookup only give one type, then don't even announce in the v4/v6 depending on the case (I know ipv6 only tracker should be very  rare...).

**Comment by arvidn** [comment]
>  I could rebuild a version with #4213 , but you said "oh, announce_endpoint is public, this would break ABI". Should I try it anyway ?

It depends on whether you depend on libtorrent-1.2 ABI or not. If you rebuild everything (including your code, calling into libtorrent) you should be OK. The ABI is relevant if you only rebuild one side of a library boundary, but leave the other built against an older version.

> And what if both are working (v4 and v6), I guess most tracker won't accept 2 announces from different ip.

I would expect most trackers to accept that. It's the only (proper) way of letting the tracker know all of your IPs.

> So my guess is some trackers only accept 1 announce from 1 ip, are rejecting one of the endpoint, but the rejecting endpoint is still trying to reannounce.

Are you sure you end up announcing from the same IP? That's not the intention.

> When ipv6 was enabled and working in libtorrent 1.1.x, how was this working ?

Not very well. If you had multiple IPv4 or multiple IPv6 addresses, it wouldn't announce all of them. libtorrent would try to announce multiple times, but the concept of multi-homed was tacked-on as an after thought. It would also pass on *one* IPv4 and *one* IPv6 address as parameters. This was problematic partly because of information leakage but also wasn't a general solution, in case of having multiple external IPs.

> Maybe that can be a part of a better behaviour, test if the resolved address is v4 or v6, and if the lookup only give one type, then don't even announce in the v4/v6 depending on the case (I know ipv6 only tracker should be very rare...).

I don't understand this suggestion. Clearly you cannot connect *from* and IPv6 address *to* an IPv4 address. If the tracker doesn't resolve to a v6 address, you won't announce to it from a v6 interface. What you're describing sounds like the current behavior. If you don't see this behavior, please help describe what you do to reproduce it. It doesn't happen by default with `client_test`. Additionally, `simulation/test_tracker.cpp` has a number of tests to verify that this is the behavior.

> For cases where both are supported, I don't know... Maybe if one endpoint is working, don't even try another one ?

But then peers won't be able to connect to you on one of your IPs. I don't see how that's an acceptable solution (nor what the problem would be actually).
