### ISSUE TITLE
libtorrent not honouring announce_to_all_trackers settings

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4302]
libtorrent version (or branch):
1.2.3
platform/architecture:
Windows 10
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

In Qbit latest version 4.2.1 using libtorrent 1.2.3 if you set Announce to all trackers to false libtorrent still announcing to all trackers in same tier. If downgraded to 4.1.9.1 which use libtorrent 1.1x this problem doesn't exist. So I'm suspecting the problem is with libtorrent 1.2.3.

**Comment by arvidn** [comment]
I'm trying to reproduce this by [extending the unit tests](https://github.com/arvidn/libtorrent/pull/4306), and I cannot. There's a possibility this is an issue on qBT. Could you provide some more details on the behavior and the expected behavior?
Are you certain of the tiers the trackers belong to?

**Comment by arvidn** [comment]
for instance, are you sure all trackers are not part of different tiers? perhaps the `announce_to_all_tiers` changed its default between qbt-4.1.9 and qbt-4.2.1. Could you try changing the `announce_to_all_tiers` setting as well?

**Comment by an0n666** [comment]
Ok I found an interesting thing. When I bind Qbit to a specific interface and specific IP address it honours the settings. But when we bind to all interfaces it announces to all trackers.

**Comment by arvidn** [comment]
interesting. This really overlaps with what I've been working on fixing for 1.2.4. It would be great if you would have a chance to try a recent build. However, I don't think this issue is fixed, but I think I know what's going on.

The way multi-homing support works is by *attempting* to announce from all source IP addresses, but under normal circumstances, only one will work and the other ones will be considered "no route to host". I bet this failure of specific endpoints for a tracker spills over into the whole tracker being considered not working. If a tracker isn't working, the next one in the tier is tried.

I think the logic needs to be that *all* endpoints for a tracker fail before the tracker is considered failed.

**Comment by an0n666** [comment]
So who's considering the tracker as failed when one of the endpoints fail? Qbit or lib?
If Qbit decides that then the issue has to be fixed on their end. I tried with Qbit master as well which contains this PR but it doesn't fix the multi announce issue. 
https://github.com/qbittorrent/qBittorrent/pull/11637

**Comment by arvidn** [comment]
Here's an attempt to fix this: https://github.com/arvidn/libtorrent/pull/4310
There may be more updates to this patch, but at least the unit tests I added suggests that this is a step in the right direction.

**Comment by an0n666** [comment]
> Here's an attempt to fix this: #4310
> There may be more updates to this patch, but at least the unit tests I added suggests that this is a step in the right direction.

Let me know when you merge it. Will test and confirm if it works.

**Comment by arvidn** [comment]
it has landed in `RC_1_2` now

**Comment by an0n666** [comment]
Nice! Is 1.2.4 release coming soon? Or the RC_1_2 branch is stable?

**Comment by arvidn** [comment]
yes, I will cut 1.2.4 tonight or tomorrow. Unless something comes up

**Comment by an0n666** [comment]
Tried to build RC_1_2 but failed.
cmd:
b2 -q --without-python --toolset=msvc-14.1 address-model=64 variant=release link=static runtime-link=static debug-symbols=on encryption=on crypto=openssl openssl-version=1.1 logging=off dht=on windows-version=win7 boost-link=static -sBOOST_ROOT="G:\qBittorrent\boost_1_71_0" include="G:\QBITTORRENT\install_msvc64\base\include" include="G:\QBITTORRENT\boost_1_71_0" library-path="G:\QBITTORRENT\install_msvc64\base\lib" library-path="G:\QBITTORRENT\boost_1_71_0\stage\lib" --prefix="G:\QBITTORRENT\install_msvc64\base" cxxflags="-O1 -Gy -Gw -GL" define=BOOST_ASIO_DISABLE_CONNECTEX linkflags="/NOLOGO /DYNAMICBASE /NXCOMPAT /LTCG /OPT:REF /OPT:ICF=5 /MANIFEST:EMBED /INCREMENTAL:NO" --hash -j 6
output:
Jamroot.jam:1: syntax error at EOF
CXXFLAGS =
LDFLAGS =
OS = NT
building boost from source directory:  G:\QBITTORRENT\boost_1_71_0
Performing configuration checks

    - default address-model    : 32-bit
    - default architecture     : x86
...patience...
...patience...
...patience...
...found 3234 targets...
...updating 165 targets...
msvc.write-setup-script bin\standalone\msvc\2f9fc86aaa675882ac74655a32fbce46\msvc-setup.bat
compile-c-c++ G:\QBITTORRENT\boost_1_71_0\bin.v2\libs\system\build\d3dbd6d6b4448a71f1ea556b7815fb08\error_code.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
error_code.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\assert.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
assert.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\bandwidth_limit.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
bandwidth_limit.cpp
msvc.archive G:\QBITTORRENT\boost_1_71_0\bin.v2\libs\system\build\d3dbd6d6b4448a71f1ea556b7815fb08\libboost_system-vc141-s-x64-1_72.lib
LINK : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\bandwidth_queue_entry.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
bandwidth_queue_entry.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\bandwidth_manager.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
bandwidth_manager.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\bdecode.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
bdecode.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\bitfield.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
bitfield.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\announce_entry.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
announce_entry.cpp
src\announce_entry.cpp(58): error C2614: 'libtorrent::announce_endpoint': illegal member initialization: 'enabled' is not a base or member

    call "bin\standalone\msvc\2f9fc86aaa675882ac74655a32fbce46\msvc-setup.bat"  >nul
 cl /Zm800 -nologo @"bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\announce_entry.obj.rsp"

...failed compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\announce_entry.obj...
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\close_reason.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
close_reason.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\bloom_filter.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
bloom_filter.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\alert_manager.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
alert_manager.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\chained_buffer.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
chained_buffer.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\alert.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
alert.cpp
src\alert.cpp(898): error C2838: 'handshake': illegal qualified name in member declaration
src\alert.cpp(898): error C2065: 'handshake': undeclared identifier
src\alert.cpp(899): error C2838: 'sock_option': illegal qualified name in member declaration
src\alert.cpp(899): error C2065: 'sock_option': undeclared identifier
src\alert.cpp(898): error C2051: case expression not constant
src\alert.cpp(899): error C2051: case expression not constant
src\alert.cpp(2589): error C2078: too many initializers
src\alert.cpp(2612): error C2653: 'socks5_alert': is not a class or namespace name
src\alert.cpp(2614): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
src\alert.cpp(2617): error C2550: 'libtorrent::socks5_alert': constructor initializer lists are only allowed on constructor definitions
src\alert.cpp(2617): warning C4508: 'libtorrent::socks5_alert': function should return a value; 'void' return type assumed
src\alert.cpp(2619): error C2653: 'socks5_alert': is not a class or namespace name
src\alert.cpp(2620): error C2270: 'message': modifiers not allowed on nonmember functions
src\alert.cpp(2623): error C2065: 'op': undeclared identifier
src\alert.cpp(2623): error C2065: 'error': undeclared identifier
src\alert.cpp(2623): error C2065: 'ip': undeclared identifier
src\alert.cpp(2622): warning C4473: 'snprintf' : not enough arguments passed for format string
src\alert.cpp(2622): note: placeholders and their parameters expect 3 variadic arguments, but 0 were provided
src\alert.cpp(2622): note: the missing variadic argument 1 is required by format string '%s'
src\alert.cpp(2715): error C2653: 'socks5_alert': is not a class or namespace name

    call "bin\standalone\msvc\2f9fc86aaa675882ac74655a32fbce46\msvc-setup.bat"  >nul
 cl /Zm800 -nologo @"bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\alert.obj.rsp"

...failed compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\alert.obj...
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\error_code.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
error_code.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\disk_buffer_holder.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
disk_buffer_holder.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\block_cache.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
block_cache.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\disk_io_thread_pool.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
disk_io_thread_pool.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\platform_util.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
platform_util.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\http_parser.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
http_parser.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\file.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
file.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\hasher.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
hasher.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\lazy_bdecode.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
lazy_bdecode.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\ip_voter.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
ip_voter.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\read_resume_data.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
read_resume_data.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\peer_list.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
peer_list.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\http_seed_connection.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
http_seed_connection.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\time.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
time.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\session.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
session.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\timestamp_history.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
timestamp_history.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\settings_pack.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
settings_pack.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\socket_type.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
socket_type.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\ConvertUTF.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
ConvertUTF.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\storage_piece_set.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
storage_piece_set.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\peer_class_set.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
peer_class_set.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\session_stats.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
session_stats.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\proxy_settings.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
proxy_settings.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\ed25519\src\ge.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
ge.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\enum_net.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
enum_net.cpp
src\enum_net.cpp(808): error C2039: 'source_hint': is not a member of 'libtorrent::ip_route'
G:\QBITTORRENT\install_msvc64\base\include\libtorrent/enum_net.hpp(71): note: see declaration of 'libtorrent::ip_route'
src\enum_net.cpp(808): error C2039: '__this': is not a member of 'libtorrent::ip_route'
G:\QBITTORRENT\install_msvc64\base\include\libtorrent/enum_net.hpp(71): note: see declaration of 'libtorrent::ip_route'

    call "bin\standalone\msvc\2f9fc86aaa675882ac74655a32fbce46\msvc-setup.bat"  >nul
 cl /Zm800 -nologo @"bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\enum_net.obj.rsp"

...failed compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\enum_net.obj...
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\torrent_info.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
torrent_info.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\ed25519\src\sign.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
sign.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\kademlia\ed25519.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
ed25519.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\utp_socket_manager.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
utp_socket_manager.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\peer_info.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
peer_info.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\sha512.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
sha512.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\kademlia\dht_state.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
dht_state.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\kademlia\item.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
item.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\ut_metadata.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
ut_metadata.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\kademlia\node_id.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
node_id.cpp
compile-c-c++ bin\f3dc1efff6c0181cbd0130ed47b9ea63\src\kademlia\rpc_manager.obj
cl : Command line warning D9025 : overriding '/O2' with '/O1'
rpc_manager.cpp
...failed updating 3 targets...
...updated 56 targets...

**Comment by arvidn** [comment]
It looks like you are picknick up headset filés from an older version of libtorrent

**Comment by an0n666** [comment]
Thanks! Forgot to clean previous build.

**Comment by skuizy** [comment]
I'm still getting "No route to host" errors on latest build from launchpad :
```
16:09:04.130 [DEBUG   ][deluge.core.torrentmanager          :1393] Tracker Error Alert: torrent (url to my tracker)[10.0.0.37:64270] No route to host "" (1) [No route to host]
```

In my setup, Deluge is running as a specific user whose default routing table send all traffic to a vpn. This setup was working great for ages and still working great if I log as this user and access https://www.ripe.net/ : it shows my vpn public address.

**Comment by arvidn** [comment]
is `10.0.0.37:64270` your IP address assigned for the VPN?
does the tracker resolve to an IPv4 address? (I would expect that it does).
Do you get any other tracker alerts that indicate success?

**Comment by skuizy** [comment]
> 
> 
> is `10.0.0.37:64270` your IP address assigned for the VPN?
Yes

> does the tracker resolve to an IPv4 address? (I would expect that it does).
Definitely

> Do you get any other tracker alerts that indicate success?
Nope... I have 3 torrents that finished correctely this week, but it was with several public trackers and I don't have relevant logs anymore to see if it was from DHT or not...

**Comment by an0n666** [comment]
I had the same kind of issue due to bad DNS server.

**Comment by skuizy** [comment]
It doesn't come from my DNS (selfhosted recursive pi-hole btw) :
```
[~]$ dig tracker.coppersurfer.tk

; <<>> DiG 9.11.5-P4-5.1ubuntu2.1-Ubuntu <<>> tracker.coppersurfer.tk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55255
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;tracker.coppersurfer.tk.       IN      A

;; ANSWER SECTION:
tracker.coppersurfer.tk. 3600   IN      A       62.138.0.158

;; Query time: 91 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Feb 08 19:35:13 CET 2020
;; MSG SIZE  rcvd: 68

[~]$ sudo -u vpn dig tracker.coppersurfer.tk
[sudo] password for odroid:

; <<>> DiG 9.11.5-P4-5.1ubuntu2.1-Ubuntu <<>> tracker.coppersurfer.tk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2932
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;tracker.coppersurfer.tk.       IN      A

;; ANSWER SECTION:
tracker.coppersurfer.tk. 3582   IN      A       62.138.0.158

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Feb 08 19:35:31 CET 2020
;; MSG SIZE  rcvd: 68
```

**Comment by arvidn** [comment]
thanks for reporting this! fixed here: https://github.com/arvidn/libtorrent/pull/4320

**Comment by arvidn** [comment]
please give it another try now!
