### ISSUE TITLE
Trackers stop working

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4487]
**Please provide the following information**

libtorrent version (or branch):
1.2.5
platform/architecture:
Windows 10
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Trackers stop working sometimes and doesn’t start working again until client is restarted or trackers are force reannounced. This happens specially when it’s running overnight and I end up with no seedbonus in the trackers I’m seeding the torrents. Peer connections and download upload as well as DHT remains functional.
I’m not 100% sure but this could be due to connection drop. Probably the endpoints/tracker gets deprioritized or backed off from hostname lookups.

**Comment by arvidn** [comment]
is it possible you have intermittent `NXDOMAIN` hostname lookup responses for the trackers?

I recently added https://github.com/arvidn/libtorrent/commit/94d90ce96f98e100cce1e93ed495c7865cede358

`NXDOMAIN` would only be expected if the DNS server explicitly responded with the domain not existing though

**Comment by an0n666** [comment]
I’m not sure about that. It stops working suddenly and remains in that state until restarted.
A lot of users are facing the same issue as mine.

**Comment by arvidn** [comment]
and I take it we don't have access to error messages, right?

**Comment by an0n666** [comment]
No we don’t. And there’s no indication whatsoever that a tracker has been disabled or not.

**Comment by an0n666** [comment]
@arvidn I just noticed that in qBt it’s showing next announce time in 5 hours whereas the tracker has a 30 min announce interval. Tracker is showing not working without any messages.

**Comment by an0n666** [comment]
Here’s the screenshot https://ibb.co/0KZ2gNg

Check the reannounce in time.

**Comment by an0n666** [comment]
Ok I just checked the nslookup response and the TTL for the domain was set to only 2 seconds. I contacted the admin and he said he forgot to increase it after a record change. Now he has set it to 12 hrs. I think the short TTL was causing intermittent NXDomain. I’ll report here again in 24 hrs if there’s any development.

**Comment by arvidn** [comment]
interesting. Yeah, I believe I experienced an NXDomain when running on privateinternetaccess VPN, with their DNS server as well. I think the error code I check for may be conflating authoritative host-not-found and non-authoritative ones. I will need to look into this a bit more, and likely revert that change

**Comment by chchia** [comment]
https://github.com/qbittorrent/qBittorrent/issues/12358

**Comment by chchia** [comment]
@arvidn I tried to isolate if this is QB or Libtorrent problem, i hope this can help to resolve the problem.

since i know that the early march i compiled docker version for my synology NAS was still working correctly, so this is what i do:

1. I made both my QBittorrent and Libtorrent to these 20th March commit
https://github.com/arvidn/libtorrent/commit/67b99b28cbac11124ff862684a4acfe2f0023b18
https://github.com/qbittorrent/qBittorrent/commit/598c856c882e8b8de1fbb254a922442ab3c4abed 
compiled, run in docker, my QB have about 20 torrents and 2 of it showing Tracker "Not Working", and about 1 hours later, all torrent show Tracker "Not Working". my PT server show correctly the 0 connected torrent.

2. i pulled latest Libtorrent, and back the QBittorrent to 10th Marh commit, compiled and run in docker, my QB have about 20 torrents and 2 of it showing Tracker "Not Working", and about 1 hour later, all torrent show Tracker "Not Working". my PT server show correctly the 0 connected torrent.

3. I pulled latest QBtorrent commit, and back the libtorrent to https://github.com/arvidn/libtorrent/commit/0f337b9ce7a1b0fc87f48843933b1c5c4dd5a9ec
compiled, and on first run, it already shown all Tracker is working. and it is already about 3 hours running, and so far all torrent is working correctly, my PT server show correctly the number of connected torrent.

based on this inmature study, it looks like some recent commit in libtorrent caused ths issues.

possible between 
https://github.com/arvidn/libtorrent/commit/0f337b9ce7a1b0fc87f48843933b1c5c4dd5a9ec
and this
https://github.com/arvidn/libtorrent/commit/67b99b28cbac11124ff862684a4acfe2f0023b18
something caused problem that make QBittorrent failed to communicate to server.

 i will try to pull few more commit between these two and see if i have any chance to find out where is the problem. but docker compilation really take time, 1 hours every compile and i take 2~3 hours to test every revision.

**Comment by an0n666** [comment]
@chchia why don’t you try with latest libtorrent commits which reversed the NXDomain backoff.

**Comment by chchia** [comment]
> @chchia why don’t you try with latest libtorrent commits which reversed the NXDomain backoff.

already tried that in step 2 above.

**Comment by chchia** [comment]
https://github.com/qbittorrent/qBittorrent/issues/12475#issuecomment-612556760

**Comment by chchia** [comment]
no good, after overnight running, arvidn/libtorrent@0f337b9 was also showing Tracker "Not Working" this morning. i will try to back the libtorrent to much earlier commit.

![image](https://user-images.githubusercontent.com/1291771/79059648-14e69c00-7caf-11ea-9f0e-2ddd76caadfa.png)

but i also notice something, anothere private-tracker-server is still working...... could this be server side problem? i am not sure but transmission 2.94 and deluge 1.3.5 was ok....

**Comment by arvidn** [comment]
@chchia did you try a build with this commit in it? https://github.com/arvidn/libtorrent/commit/11b19ac813161a4bb939b5324dd295fdbc9861bd

That's where I undo the change I suspect caused this issue.

**Comment by chchia** [comment]
> @chchia did you try a build with this commit in it? [11b19ac](https://github.com/arvidn/libtorrent/commit/11b19ac813161a4bb939b5324dd295fdbc9861bd)
> 
> That's where I undo the change I suspect caused this issue.

Hi @arvidn , i come across those issues:

https://github.com/arvidn/libtorrent/issues/4412
https://github.com/arvidn/libtorrent/issues/4325
https://github.com/qbittorrent/qBittorrent/issues/12443
https://github.com/qbittorrent/qBittorrent/pull/12484

so i changed the setting inside QB, and running QB+libtorrent latest commit, and it had been stable for 11 hours. 
![image](https://user-images.githubusercontent.com/1291771/79072052-85bea000-7d11-11ea-8a9e-bb56e56f3167.png)

I will let it run until 24 hours, and will report again if it fail again.

**Comment by arvidn** [comment]
It sounds like this issue is resolved by reverting the NXDOMAIN patch

**Comment by julian-alarcon** [comment]
So, should this be marked as closed with your PR https://github.com/arvidn/libtorrent/pull/4514 ?

**Comment by arvidn** [comment]
That's my impression. Unless someone is still experiencing this issue with that patch applied.

**Comment by chchia** [comment]
can you please wait 2 more days, i am still getting Tracker Not Working with the latest commit yesterday. i am trying to figure out if this is server side problem or not.

thank you.

**Comment by chchia** [comment]
i am sorry, kind please close this...

very unfortunately i still receive tracker "not working" within 24 hours of my restart of QB4.3a1. but only to one specific tracker, other tracker seems OK.

could be that tracker server is imcompatible? but QB4.2.1, transmission 2.94 and deluge 1.3.5 is ok. i did not try deluge 2 yet but i guess should be alright as well.

i might having seperate issues not related to this. kindly close this and thank you so much.

**Comment by arvidn** [comment]
thanks for testing and reporting!
