### ISSUE TITLE
Micro Transport Protocol (μTP) seemingly causing Realtek 2.5GbE controllers to reset (Event ID 10400, source NDIS)?

### ISSUE THREAD

**Issue by article10** [arvidn/libtorrent#5761]
**Please provide the following information**

**libtorrent version (or branch):**

libtorrent-rasterbar | 1.2.11+gitafa406f890
qBittorrent v4.3.1

platform/architecture:
Windows 10 20H2

compiler and compiler version:
Unknown (the one used by the build at https://www.qbittorrent.org/download.php) 

**please describe what symptom you see, what you would expect to see instead and
how to reproduce it.**

I was advised by the qBittorrent team to report the initial issue (https://github.com/qbittorrent/qBittorrent/issues/14019) to libtorrent, since _"this is more appropriate for the libtorrent issue tracker, which is where qBittorrent gets the uTP implementation from: https://github.com/arvidn/libtorrent"_ 

**_What is the problem_**

Ethernet connection dropping. Windows Event Viewer showing errors with Event ID: 10400, source NDIS:
_'The network interface "Realtek Gaming 2.5GbE Family Controller" has begun resetting. There will be a momentary disruption in network connectivity while the hardware resets. Reason: The network driver detected that its hardware has stopped responding to commands. This network interface has reset 61 time(s) since it was last initialized.'_

**_What is the expected behavior_**

No network interface resets due to hardware becoming non-responsive.

**_Steps to reproduce_**

Have a motherboard with 2.5GbE Ethernet adapter by Realtek.
In my case "Realtek Gaming 2.5GbE Family Controller"
Hardware IDs:
PCI\VEN_10EC&DEV_8125&SUBSYS_E0001458&REV_05
PCI\VEN_10EC&DEV_8125&SUBSYS_E0001458
PCI\VEN_10EC&DEV_8125&CC_020000
PCI\VEN_10EC&DEV_8125&CC_0200

Start qBittorrent and let it run for a while in the background (with the Micro Transport Protocol or μTP protocol enabled?). It seems to occur more often when also using the PC with different apps at the same time, e.g. streaming video from YouTube in Firefox.

The connection will eventually drop. Using the "Troubleshoot problems" on the Network Internet access icon in the Windows 10 tray resets the network adapter and restores connectivity, until it happens again.

Windows Event Viewer will be showing Event ID: 10400 errors shown above. And some DNS Client Event 1014 such as "Name resolution for the name tracker.publicbt.com timed out".
Extra info(if any)

Event log screenshot (example): https://i.imgur.com/1RhE7Ij.png
Realtek Gaming 2.5 GbE Family Controller driver version 10.39.212.2020 (comes with Windows 10). Also tried with Realtek https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software

Issue reported across motherboard manufacturers forums:

ASRock: http://forum.asrock.com/forum_posts.asp?TID=14888&PN=4&title=realtek-25gbe-rtl8125-ndis-reset-problem where one of the last posts mentions: "I found the solution 1 week ago: I hope you have a torrent client on your machine guys? Because **the problem is caused by μTP (Micro Transport Protocol).** I use qBittorrent and since I switched the peer connection protocol to TCP only, the problem has disappeared, it has never been produced since, so I dare say that this was the problem. "

MSI : https://forum-en.msi.com/index.php?threads/realtek-pcie-2-5gbe-family-controller-resetting.345823/ with one of the last posts mentioning: "I can confirm I was using **qbittorent** when I had those issues too ! I'm gonna forward this to MSI."

Gigabyte Reddit they do as well: https://www.reddit.com/r/gigabyte/comments/hl8jig/z490_elite_ac_the_network_interface_has_begun/ "Also it seems to happen way more frequently when I stress the card using **qBittorrent**, like every minute or so."

XML of the error below:
[xmloftherror.txt](https://github.com/arvidn/libtorrent/files/5725609/xmloftherror.txt)
![102726268-acf85300-431d-11eb-8ee3-910eeb464e3a](https://user-images.githubusercontent.com/13686379/102804294-db2b7080-43b9-11eb-9790-66e7da61a7f8.png)

**Comment by TerAnYu** [comment]
The problem persists on qBittorrent v4.3.2.

**Comment by arvidn** [comment]
I suspect the hardware or driver isn't well tested under heavy UDP load, and fails. I don't really see anything actionable on libtorrent's part, other than recommending that users with the failing hardware either disable uTP or replace the hardware.

libtorrent doesn't talk directly to the driver, it uses the operating system's API. The API guarantees that hardware is not supposed to reset by its use, similar to operating systems (normally) guaranteeing they won't kernel-panic because of system calls.

**Comment by TerAnYu** [comment]
Thanks for the answer.
Yesterday I was upset that the network was constantly disconnecting, so without any thoughts I found that this was already discussed, without thinking that the drivers were to blame.
Yes, disabling UDP helped, also allowed to increase the speed of the content given (where I was before...).

**Comment by kpakozz96pyc** [comment]
This problem also happens not only for qbittorrent, sometimes get it while playing World of Warcraft.
Motherboard: Gigabyte B550 AORUS ELITE V2
Ethernet adapter: Realtek Gaming 2.5GbE Family Controller
OS: Windows 10 Pro 20H2 build 19042.685
Driver: 10.39.212.2020

**Comment by 1265578519** [comment]
禁用UTP，使用仅TCP传输即可解决

**Comment by arvidn** [comment]
english please. machine-translated:

> 8125 2.5G network card uses openwrt routing PT download to reach 30MB/S, the network card is broken and the solution is dead
> 
> Solution 1
> Replace the router, use a non-openwrt router, such as tp routing, millet routing, etc. are based on openwrt, so there will be problems
> If there is no tp router, you can try to remove the openwrt router and connect the optical modem directly to solve the problem
> 
> Solution 2
> Enter the BT client, in the settings, turn off UTP transmission. UTP is a transmission protocol algorithm based on UDP. The problem caused by the lack of support for UDP transmission due to a problem with the openwrt router firmware, the problem can be solved by simply using TCP transmission

**Comment by Seeker2** [comment]
DHT might be a problem as well, since it also uses UDP packets.
udp trackers do too, but at least those shouldn't be called as often as DHT or uTP traffic.

Is there any IPv6 traffic?
...because it wouldn't surprise me if the problem only happens with UDP traffic on IPv6.

**Comment by GnusinPavel** [comment]
I don't use any torrent client and have the same issue. 
Morheboard - MSI MAG Tomahawk b460
Ethernet connection dicsonnected randomly. Motherboard has two network adapters Intel and Real Tech, both of them have the same issue from time to time. I can fix that only if  I plug out ethernet cabel and plug in. After some time issue repeats again.  ((
Intalled last version of drivers and issue had not gone ((

**Comment by article10** [comment]
> 
> 
> I don't use any torrent client and have the same issue.
> Morheboard - MSI MAG Tomahawk b460
> Ethernet connection dicsonnected randomly. Motherboard has two network adapters Intel and Real Tech, both of them have the same issue from time to time. I can fix that only if I plug out ethernet cabel and plug in. After some time issue repeats again. ((
> Intalled last version of drivers and issue had not gone ((

Considering you are on an **MSI motherboard**, in the MSI forum, an administrator also posted a Realtek 2.5GbE beta driver: https://forum-en.msi.com/index.php?threads/realtek-pcie-2-5gbe-family-controller-resetting.345823/page-4#post-2032005
Can you go test it and share your experience there?

For other users: A supposed beta driver was also posted by a user in the Tweaktown **GIGABYTE** thread: https://www.tweaktownforum.com/forum/tech-support-from-vendors/gigabyte/28656-gigabyte-latest-beta-bios?p=976471#post976471

Perhaps the disconnect Event ID 10400, NDIS issue was finally acknowledged by Realtek? One can hope.

Until we have some verification, please keep this issue ID open until users are able to confirm that this was a driver issue solved with an official driver update.

**Comment by Uqen** [comment]
I don't download anything but I play games, and the beta driver on the msi forum didn't help with my asrock b450m pro4 mobo, which uses the realtek gbe family version but still has the same errors & usually the same exact drivers. At first it seemed to have worked but after trying Overwatch (because the disconnects happen the most in that game) I was quick to realize that it didn't fix it for me - unfortunately. If anyone could also check it while playing games, not torrenting, it would be appreciated.

**Comment by iandk** [comment]
Same issue here with my X470 Gaming Plus MAX.

Occurs from time to time in Battlefield 4-

**Comment by BonScott84** [comment]
had couple of disconnection some weeks ago
i m using aorus b550i with realtek 8125, but i had only 2 in windows. In linux seems to be fine since the beginning but... the last realtek windows driver sat ethernet at 1g max full speed, so i suppose installing the linux driver (using mint i have to) the sat 1g also in the linux driver
happened 2 times downloading, but never happened playing online for hours, literally playing for hours no issue

**Comment by article10** [comment]
Update: On the MSI forums it was posted that Realtek is asking for someone to e-mail them Wireshark captures to identify the problems with the RTL8125B(G) on the AMD B550 platform:

https://forum-en.msi.com/index.php?threads/realtek-pcie-2-5gbe-family-controller-resetting.345823/page-11#post-2041042

**Comment by BonScott84** [comment]
Thank you, i think i can do it, i experimented a network breakdown, repetely, if i download full bw from steam while me and my girlfriend we are working on different systems and PCs
