### ISSUE TITLE
100% of CPU core is used when torrent with mix of I2P and non-I2P trackers is added

### ISSUE THREAD

**Issue by Vort** [arvidn/libtorrent#7535]
This problem can be reproduced with I2P mode **disabled**.
Just run `client_test` with default parameters, like this: `client_test --alert_mask=all` and add such magnet link:
`magnet:?xt=urn:btih:70260ca39b2867a59f46d81db85eecb256b9365c&dn=I2P%20Update%202.1.0&tr=http%3A%2F%2Ftracker2.postman.i2p%2Fannounce.php&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce`
Then observe CPU usage.

I suspect hang may be realted to function `libtorrent::torrent::update_tracker_timer`.

_libtorrent version (or branch):_ 5ce4c516479085eda9327d35891b7732d6d5037b
_platform/architecture:_ Windows x64
_compiler and compiler version:_ clang version 15.0.7

**Comment by ukoz** [comment]
confirm 1 core 100% 2nd 50%, not going past 'no metadata'
 209 win64 MSVS 17.7.3

**Comment by luzpaz** [comment]
soft bump

**Comment by absolutep** [comment]
Here is the fix - it solved for me atleast in both "mixed mode" as well as "I2P-only mode"

https://github.com/qbittorrent/qBittorrent/discussions/21926

**Comment by Vort** [comment]
> Here is the fix - it solved for me atleast in both "mixed mode" as well as "I2P-only mode"

This is not a fix, it is avoidance of the problem.

**Comment by Neustradamus** [comment]
@arvidn has done a recent PR about I2P:
- https://github.com/arvidn/libtorrent/pull/7831

**Comment by Neustradamus** [comment]
.

**Comment by absolutep** [comment]
unstale this

**Comment by milahu** [comment]
fixed by #7950 

the old version was bottlenecking at `is_i2p_url`

the new version is bottlenecking at

```
libtorrent::aux::torrent::update_tracker_timer
libtorrent::aux::torrent::announce_with_tracker
boost::asio::detail::timer_queue
libtorrent::aux::session_settings::get_bool
```

these functions are also mentioned in #7898

i get 100% cpu load seeding 4K torrents
quickfix: use multiple network threads https://github.com/arvidn/libtorrent/issues/7894#issuecomment-2893483860

edit: this was with the non-default [libtorrent settings](https://www.libtorrent.org/reference-Settings.html)
`announce_to_all_tiers = true`
`announce_to_all_trackers = true`
which obviously cause more cpu load...
with the default settings (both `false`) i see 5% cpu load seeding 4K torrents

**Comment by Neustradamus** [comment]
@Vortn, @ilayanyatto72733: Can you confirm that this PR has fixed the problem?
- https://github.com/arvidn/libtorrent/pull/7950

**Comment by Vort** [comment]
> Can you confirm that this PR has fixed the problem?

I'm not using torrents right now, sorry. I hope other people can perform tests for this issue.

**Comment by ErebosGR** [comment]
CPU usage was normal while running I2P Mixed Mode properly (v5.1.4 lt2.0).
As soon as I uninstalled i2pd, and disabled I2P in qBittorrent, one CPU core gets stuck at 100% usage until I exit qBittorrent.

edit: With i2pd uninstalled, I enabled I2P in qBittorrent again and my issues were resolved... The trackers are not stuck at "Not Contacted Yet" and CPU usage went back down to idle levels.

**Comment by milahu** [comment]
> Can you confirm that this PR has fixed the problem

no, i still get 100% cpu usage (+15 watts) with

- libtorrent aa59c7c583e00e7b91f324d0792279d4637ab899 ([libtorrent.nix](https://github.com/milahu/nur-packages/blob/a7e0466c2d6dc3210ad7b923433d2c548a82a314/pkgs/by-name/li/libtorrent-rasterbar-2_1_x/package.nix#L28))
  - with https://github.com/arvidn/libtorrent/pull/7950
- qbittorrent https://github.com/qbittorrent/qBittorrent/commit/e154c1a811021ab0bd6e6f9595c2b3c6518aaea3 ([qbittorrent.nix](https://github.com/milahu/nur-packages/blob/a7e0466c2d6dc3210ad7b923433d2c548a82a314/pkgs/applications/networking/p2p/qbittorrent/default.nix#L31))
  - with https://github.com/qbittorrent/qBittorrent/pull/23953

```
git clone --depth=1 https://github.com/milahu/nur-packages
cd nur-packages
nix-build . -A qbittorrent-debug
perf record -F 100 -g ./result/bin/qbittorrent # generate perf.data
perf report # visualize perf.data
```

[perf.data.xz.gz](https://github.com/user-attachments/files/26330562/perf.data.xz.gz)

`perf report` shows the usual suspects

```
+   84,80%     0,36% libtorrent::torrent::update_tracker_timer
+   84,77%     0,28% void boost::asio::detail::handler_work
+   84,45%     0,58% void libtorrent::torrent::wrap
+   83,88%     4,90% libtorrent::torrent::on_tracker_announce
+   74,45%     2,29% libtorrent::torrent::announce_with_tracker
+   25,90%     1,14% libtorrent::is_i2p_url
+   21,95%     0,30% libtorrent::
+   13,77%     2,07% libtorrent::torrent::update_tracker_timer
+   13,64%     2,08% libtorrent::parse_url_components
```

config:
announce_to_all_tiers = false (default)
announce_to_all_trackers = false (default)
I2P is disabled (default)

4000 seeding torrents
no torrents have i2p trackers
some torrents have http trackers - maybe http trackers are the problem?

<details>
<summary>
print-trackers.py
</summary>

```py
#!/usr/bin/env python3

# debug: print trackers of torrents in qBittorrent

import os
import json
import qbittorrentapi

# example config:
"""
{
  "host": "127.0.0.1",
  "port": 9001,
  "username": "admin",
  "password": "xxx"
}
"""
qbt_config_path = os.path.expanduser("~/.config/qbittorrentapi.json")
with open(qbt_config_path) as f:
    conn_info = json.load(f)

qbt_client = qbittorrentapi.Client(**conn_info)

tracker_urls = dict()
# https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html#qbittorrentapi.torrents.TorrentsAPIMixIn.torrents_info
for torrent in qbt_client.torrents_info(status_filter="seeding"):
  for tracker in torrent.trackers:
    if tracker.tier == -1: continue # dht pex lsd
    if tracker.url in tracker_urls:
      tracker_urls[tracker.url] += 1
    else:
      tracker_urls[tracker.url] = 1
tracker_urls = list(tracker_urls.items())
# sort by count descending
tracker_urls.sort(key=lambda x: -1*x[1])
for url, count in tracker_urls:
  print(count, url)
```

</details>


<details>
<summary>
trackers
</summary>

```
2433 udp://107.189.2.131:1337/announce
99 udp://tracker.coppersurfer.tk:6969/announce
93 http://bt3.t-ru.org/ann?magnet
88 http://bt4.t-ru.org/ann?magnet
85 udp://tracker.opentrackr.org:1337
84 http://bt.t-ru.org/ann?magnet
78 http://bt2.t-ru.org/ann?magnet
68 udp://open.stealth.si:80/announce
67 udp://tracker.tiny-vps.com:6969/announce
65 udp://9.rarbg.to:2710/announce
55 udp://tracker.openbittorrent.com:6969/announce
55 udp://9.rarbg.me:2780/announce
53 udp://9.rarbg.to:2730/announce
53 http://p4p.arenabg.com:1337/announce
51 udp://tracker.cyberia.is:6969/announce
40 udp://tracker.internetwarriors.net:1337/announce
38 udp://9.rarbg.to:2920/announce
25 udp://tracker.opentrackr.org:1337/announce
18 udp://ipv4.tracker.harry.lu:80/announce
16 udp://exodus.desync.com:6969/announce
16 udp://p4p.arenabg.com:1337/announce
15 udp://tracker.uw0.xyz:6969/announce
15 udp://retracker.lanta-net.ru:2710/announce
13 udp://denis.stalker.upeer.me:6969/announce
12 udp://ipv6.tracker.harry.lu:80/announce
12 udp://open.demonii.si:1337/announce
10 udp://23.134.90.9:1337/announce
10 udp://83.31.208.224:6969/announce
10 udp://135.125.202.143:6969/announce
10 udp://45.154.96.35:6969/announce
10 udp://211.75.205.187:6969/announce
10 udp://191.23.71.103:6969/announce
10 udp://37.235.176.37:2710/announce
4 http://tracker.openbittorrent.com:80/announce
4 udp://opentracker.i2p.rocks:6969/announce
4 udp://142.132.183.104:6969/announce
4 udp://tracker.dler.org:6969/announce
4 udp://tracker.moeking.me:6969/announce
4 udp://tracker1.myporn.club:9337/announce
3 http://95.107.48.115:80/announce
3 http://open.acgnxtracker.com:80/announce
3 http://t.acg.rip:6699/announce
3 http://t.nyaatracker.com:80/announce
3 http://tracker.bt4g.com:2095/announce
3 http://tracker.files.fm:6969/announce
3 http://vps02.net.orel.ru:80/announce
3 https://1337.abcvg.info:443/announce
3 https://tracker.nanoha.org:443/announce
3 https://tracker.sloppyta.co:443/announce
3 udp://37.235.174.46:2710/announce
3 udp://75.127.14.224:2710/announce
3 udp://explodie.org:6969/announce
3 udp://open.demonii.com:1337/announce
3 udp://tracker.filemail.com:6969/announce
3 udp://tracker.swateam.org.uk:2710/announce
3 udp://tracker.dump.cl:6969/announce
3 udp://tracker-udp.gbitt.info:80/announce
2 http://bt1.archive.org:6969/announce
2 http://bt2.archive.org:6969/announce
2 udp://152.231.114.209:1337/announce
2 udp://156.234.201.18:80/announce
2 udp://23.134.88.6:1337/announce
2 udp://198.100.149.66:6969/announce
2 udp://102.223.180.235:6969/announce
2 udp://185.102.219.163:6969/announce
2 udp://193.189.100.186:6969/announce
2 udp://9.rarbg.to:2780/announce
2 udp://9.rarbg.me:2730/announce
2 udp://coppersurfer.tk:6969/announce
2 udp://tracker.zer0day.to:1337/announce
2 udp://9.rarbg.com:2810/announce
2 http://tracker.opentrackr.org:1337/announce
2 udp://fe.dealclub.de:6969/announce
2 udp://movies.zsw.ca:6969/announce
2 https://opentracker.i2p.rocks:443/announce
2 udp://public.tracker.vraphim.com:6969/announce
2 udp://tracker.0x.tf:6969/announce
2 udp://tracker.pomf.se:80/announce
2 udp://tracker.srv00.com:6969/announce
2 udp://bt.ktrackers.com:6666/announce
2 udp://tracker.qu.ax:6969/announce
2 udp://tracker.ololosh.space:6969/announce
2 udp://open.free-tracker.ga:6969/announce
2 udp://ns-1.x-fins.com:6969/announce
2 udp://leet-tracker.moe:1337/announce
1 udp://wepzone.net:6969/announce
1 udp://ttk2.nbaonlineservice.com:6969/announce
1 udp://tracker2.dler.org:80/announce
1 udp://tracker.tryhackx.org:6969/announce
1 udp://tracker.therarbg.to:6969/announce
1 udp://tracker.fnix.net:6969/announce
1 udp://tr4ck3r.duckdns.org:6969/announce
1 udp://tracker.openbittorrent.com:80/announce
1 udp://tracker.bittor.pw:1337/announce
1 udp://retracker01-msk-virt.corbina.net:80/announce
1 udp://185.121.168.96:1337/announce
1 udp://44.30.4.4:6969/announce
1 http://explodie.org:6969/announce
1 http://184.105.151.164:6969/announce
1 http://78.30.254.12:2710/announce
1 http://tracker.gbitt.info/announce
1 http://tracker.nyap2p.com:8080/announce
1 https://tk.mabo.ltd:443/announce
1 udp://207.246.121.172:2000/announce
1 udp://212.47.227.58:6969/announce
1 udp://51.15.40.114:80/announce
1 udp://62.138.0.158:6969/announce
1 udp://9.rarbg.me:2710/announce
1 udp://tracker.iamhansen.xyz:2000/announce
1 udp://zephir.monocul.us:6969/announce
1 udp://212.1.226.176:2710/announce
1 udp://opentor.org:2710/announce
1 udp://open.nyap2p.com:6969/announce
1 udp://retracker.akado-ural.ru:80/announce
1 udp://retracker.netbynet.ru:2710/announce
1 udp://tracker.ds.is:6969/announce
1 udp://23.134.88.9:6969/announce
1 udp://23.134.88.9:1337/announce
1 udp://opentracker.io:6969/announce
1 udp://isk.richardsw.club:6969/announce
1 http://www.torrentsnipe.info:2701/announce
1 http://www.genesis-sp.org:2710/announce
1 http://tracker810.xyz:11450/announce
1 http://tracker.xiaoduola.xyz:6969/announce
```

</details>

**Comment by glassez** [comment]
Here is a way to reproduce this bug, provided by a `qBittorrent` user recently:

1. Disable *"I2P"* and *"Mixed Mode"* in *Settings > Connection*
2. Add a torrent containing an I2P tracker
3. Start the torrent and see your CPU getting *hogged* at permanent 100%
4. Enable the *"I2P"* option of step 1. and see that your CPU is *still* at 100%
5. Enable the *"Mixed Mode"* option of step 1., and see your **CPU not being hogged anymore.** 
**This is the current workaround (enabling these two options), even if you don't want or need to use I2P.**

**Comment by glassez** [comment]
@arvidn, ping!

**Comment by glassez** [comment]
This is how I expect I2P related options should behave:

1. If the `I2P` option is disabled, `libtorrent` should simply treat the I2P trackers as "unable to connect" and continue using regular trackers as usual.
2. If the `I2P` option is enabled, then `libtorrent` should use only I2P trackers in torrents that have such. Regular torrents should work as usual.
3. If both `I2P` and `Mixed mode` options are enabled, then `libtorrent` should just use all available trackers, both regular and I2P.

And one more important comment on the topic, which I have already made several times, but it remained ignored.
Currently, `libtorrent` behaves incorrectly in the part concerning the definition of I2P torrents. It marks torrents containing I2P trackers at the first time addition, and then simply uses this mark in the future, regardless of anything else (it even saves `i2p` flag in the resume data). This is extremely unexpected behavior. The status of the I2P torrent should change dynamically with any changes in the trackers set of torrent, as well as when resuming the torrent (i.e. do not save the `i2p` flag in the resume data).

**Comment by Neustradamus** [comment]
@arvidn: A lot of comments recently about it...
- https://github.com/qbittorrent/qBittorrent/issues/23384

Can you check it?

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/8398

**Comment by glassez** [comment]
@arvidn 
What about the following?

> And one more important comment on the topic, which I have already made several times, but it remained ignored.
> Currently, `libtorrent` behaves incorrectly in the part concerning the definition of I2P torrents. It marks torrents containing I2P trackers at the first time addition, and then simply uses this mark in the future, regardless of anything else (it even saves `i2p` flag in the resume data). This is extremely unexpected behavior. The status of the I2P torrent should change dynamically with any changes in the trackers set of torrent, as well as when resuming the torrent (i.e. do not save the `i2p` flag in the resume data).

Could you not ignore it, but at least clarify its perspective?

**Comment by arvidn** [comment]
Is there some well established behavior for this? It doesn't seem entirely unreasonable to treat a torrent as an i2p-torrent if the original version of it has trackers. Removing and adding trackers later is more of a client-side feature, and the underlying .torrent file isn't necessarily changed or re-classified.

Now, I don't really know or understand all the use cases and work-flows where a torrent can be expected to change classification.

The `i2p` flag is mostly used to enforce the mixed mode setting, right?

Is there some simplification that can be done to not need this flag at all?

**Comment by milahu** [comment]
ideally, there should be an `I2P mixed mode` setting per torrent
similar to the `private` flag, but editable by the user

otherwise the user has to run multiple libtorrent instances for different types of torrents

**Comment by arvidn** [comment]
one possibility would be to remove the `allow_i2p_mixed` and change the meaning of the `i2p` torrent flag to mean "only allow i2p peers".

Then:

* the default is still that any torrent with a .i2p tracker only allows i2p peers
* if you (explicitly) clear the flag, you allow both i2p and clear peers

It would be another backwaards compatibility issue though

**Comment by milahu** [comment]
> the default is still that any torrent with a .i2p tracker only allows i2p peers

yes, but as glassez said:
the source of truth here should be the torrent's **current** list of trackers
not the original list of trackers (which the user does not control)

- no I2P trackers &rarr; "public" torrent
- I2P trackers &rarr; "private" torrent
  - except the user has explicitly enabled `I2P mixed mode` for this torrent
- I2P trackers in the past, but no I2P trackers now &rarr; "private" torrent, because the `i2p` flag is still set, until the user explicitly clears the `i2p` flag

**Comment by arvidn** [comment]
> the source of truth here should be the torrent's current list of trackers

Why is this the most sensible/intuitive/safe option?

Is it better than an explicit flag (that defaults to be based on the trackers)

**Comment by glassez** [comment]
> yes, but as glassez said: the source of truth here should be the torrent's **current** list of trackers not the original list of trackers (which the user does not control)
> 
> * no I2P trackers → "public" torrent
> * I2P trackers → "private" torrent
>   
>   * except the user has explicitly enabled `I2P mixed mode` for this torrent
> * I2P trackers in the past, but no I2P trackers now → "private" torrent, because the `i2p` flag is still set, until the user explicitly clears the `i2p` flag

You have misinterpreted me. There should not be `i2p` flag in its current form, only `has_i2p_tracker` dynamic property that is based on current trackers set.

* no I2P trackers → `has_i2p_tracker` is `false`.
* has I2P trackers → `has_i2p_tracker` is `true` (connects only to i2p trackers or to both i2p and regular trackers, depending on the `I2P mixed mode`.

>It doesn't seem entirely unreasonable to treat a torrent as an i2p-torrent if the original version of it has trackers. 

Trackers are not part of torrent identity. There can be several different .torrent files represent the same torrent but having different set of trackers. So "i2p" isn't part of torrent identity in any reasonable way. "I2P" is essentially a dynamic property determined by current set of trackers (i.e. it is just `has_i2p_tracker`).
It makes no sense to look into the past, whether torrent had an i2p tracker before or not. This only makes sense when the current set of trackers is changed, in order to change its current mode of operation if necessary (for example, if the last i2p tracker was deleted, then start connecting to regular trackers and dht, etc.).

**Comment by milahu** [comment]
> It makes no sense to look into the past, whether torrent had an i2p tracker before or not.

it does make sense to avoid leaking I2P-private torrents into the clearnet
because trackers can be removed by accident
but okay, also an i2p flag can be removed by accident...
so this feature is optional
assuming users dont make the mistake of removing I2P trackers from I2P-private torrents

where an extra `i2p` flag is needed is with trackerless torrents
like `magnet:?xt=urn:btih:xxx&i2p=1`
because we dont want to query the clearnet DHT for I2P-private torrents
just like `private` torrents dont use the DHT
but is there an I2P-hidden DHT...? i guess no

but at least such an `i2p` parameter would make sense to tell libtorrent
"this torrent is I2P-private, so add some I2P trackers"

a per-torrent `I2P mixed mode` setting allows for a more fine-grained config

**Comment by arvidn** [comment]
@glassez is there any value in having `has_i2p_tracker` at all?

Right now, the only use if the current flag is to prevent plain peers from being added based on the mixed-mode setting.

**Comment by glassez** [comment]
> where an extra `i2p` flag is needed is with trackerless torrents
> like `magnet:?xt=urn:btih:xxx&i2p=1`

Can I2P torrent be trackerless? Is there DHT or similar way to obtain peers from I2P network?

>because we dont want to query the clearnet DHT for I2P-private torrents
just like private torrents dont use the DHT
but is there an I2P-hidden DHT...? i guess no

If it doesn't exist, then it definitely doesn't make sense.

Although it doesn't make sense to me at all, because if this flag existed as part of a magnet link, anyone could just delete it from there and then add a link to client app.

Once again, I want to focus on the fact that since "I2P mode" is not part of the identity of the torrent, it does not make sense to consider it as some kind of basic property of the torrent, it is just part of the current state.

**Comment by glassez** [comment]
> [@glassez](https://github.com/glassez) is there any value in having `has_i2p_tracker` at all?
> 
> Right now, the only use if the current flag is to prevent plain peers from being added based on the mixed-mode setting.

I was talking about `has_i2p_tracker` abstractly. It doesn't have to be some kind of flag or a separate function if it's not necessary.

**Comment by Vort** [comment]
> Can I2P torrent be trackerless? Is there DHT or similar way to obtain peers from I2P network?

With #7408 implemented - yes. Right now - no.

**Comment by glassez** [comment]
> > Can I2P torrent be trackerless? Is there DHT or similar way to obtain peers from I2P network?
> 
> With [#7408](https://github.com/arvidn/libtorrent/issues/7408) implemented - yes. Right now - no.

Having an I2P DHT (or something similar) explicitly defined I2P mode would make sense (it would not be able to work without it). In this case, I would expect that the client would be able to explicitly disable the I2P mode for specific torrents, so that if it is disabled, the torrent would not try to connect to I2P peers and trackers (if there are any in its set).

What are the forecasts that [#7408](https://github.com/arvidn/libtorrent/issues/7408) will be implemented in the foreseeable future?

**Comment by Neustradamus** [comment]
@Vort: Have you seen this merged PR?
- https://github.com/arvidn/libtorrent/pull/7831

Linked to:
- https://github.com/arvidn/libtorrent/issues/7269
- https://github.com/arvidn/libtorrent/issues/7408

**Comment by VADemon** [comment]
Thank you @glassez for the [May 18th comment](https://github.com/arvidn/libtorrent/issues/7535#issuecomment-4474869253). The current behavior is like the worst case of the worst cases in terms of usability for the user.

We have done the following in that order and had to debug ourselves out of the situation:

1. Create a torrent, add a bunch of trackers for redundancy
2. Initial tracker list-v1 ended up with lots of stale servers
3. Replace the tracker list-v1 with manually filtered entries. Add some i2p trackers to list-v2, in case anybody chooses to use i2p: it'll already be there!
    - same infohash throughout, only tracker list modified. Like glassez said, "torrent identity" does not depend on trackers
4. Load the list-v2 .torrent in qBittorrent. Silence. None of the existing seeders are picked up. As if everything stopped working
5. Removing i2p trackers helped.

Mind you, if the user omits the crucial step of completely removing & readding the torrent to client, it'll never begin to work as long as I2P is not actually being used. We've had the correct hypothesis from the start, but you can't expect this of regular users.

> Person A: i tested many combinations (old trackers only, old trackers and a single new tracker, new trackers only, new trackers plus old trackers, new trackers minus i2p, no trackers)
> all of them worked except for the ones using the new trackers WITH i2p
> as soon as i2p is removed it works
> but yeah all these tests were done removing and readding the torrent entirely

> Person B: I had also the same problem yesterday but i thought i accidentally added trackers with i2p
> I was troubleshooting for 3 hours why **it was stalling** for me yesterday and **internally in the quick resume file it flipped the i2p flag to 1**

> Person C: thats so stupid. I guess you cant mix i2p with non i2p then? cuz why would it use a global flag for the entire torrent

---

I too think the current behavior is neither correct nor intuitive, both from the standard's and user perspectives.

Yet it can be discussed whether an additional fail-safe is needed to avoid accidental "leakage" of *hidden* I2P torrents onto the clearnet... where it'll be immediately picked up and recorded by DHT crawling bots. The tracker list alone might not be a sufficient safeguard.
